
# ----------------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.5.1, generator: @autorest/powershell@3.0.466)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Gets the registered connector instances from a storage.
.Description
Gets the registered connector instances from a storage.
.Example
PS C:\> Get-CsTeamsShiftsConnectionInstance | Format-List

ConnectorId                              : 6A51B888-FF44-4FEA-82E1-839401E9CD74
ConnectorName                            : Blue Yonder
ConnectorSpecificSettingAdminApiUrl      : https://nehstdevwfm02.replgroup.com/retail/data/wfmadmin/api/v1-beta2
ConnectorSpecificSettingCookieAuthUrl    : https://nehstdevwfm02.replgroup.com/retail/data/login
ConnectorSpecificSettingEssApiUrl        : https://nehstdevfas01.replgroup.com/retail/data/wfmess/api/v1-beta1
ConnectorSpecificSettingFederatedAuthUrl : https://nehstdevfas01.replgroup.com/retail/data/login
ConnectorSpecificSettingRetailWebApiUrl  : https://nehstdevwfm02.replgroup.com/retail/data/retailwebapi/api/v1
ConnectorSpecificSettingSiteManagerUrl   : https://nehstdevfas01.replgroup.com/retail/data/wfmsm/api/v1-beta2
DesignatedActorId                        : ae319a6b-f0a7-491e-9bc1-3415bf8a1621
EnabledConnectorScenario                 : {Shift, TimeOffRequest}
EnabledWfiScenario                       : {Shift}
Etag                                     : "0000715c-0000-0700-0000-60b94c0f0000"
Id                                       : WCI-3f37d48a-95aa-45e3-99be-86d99c5f1ace
Name                                     : Maosha Connector instance1
SyncFrequencyInMin                       : 60
TenantId                                 : b9a3c751-d652-47f0-b612-9dffc7a4e800
WorkforceIntegrationId                   : WFI_8562677a-996c-4f21-9935-723ba12a8d64

ConnectorId                              : 6A51B888-FF44-4FEA-82E1-839401E9CD74
ConnectorName                            : Blue Yonder
ConnectorSpecificSettingAdminApiUrl      : https://nehstdevwfm02.replgroup.com/retail/data/wfmadmin/api/v1-beta2
ConnectorSpecificSettingCookieAuthUrl    : https://nehstdevwfm02.replgroup.com/retail/data/login
ConnectorSpecificSettingEssApiUrl        : https://nehstdevfas01.replgroup.com/retail/data/wfmess/api/v1-beta1
ConnectorSpecificSettingFederatedAuthUrl : https://nehstdevfas01.replgroup.com/retail/data/login
ConnectorSpecificSettingRetailWebApiUrl  : https://nehstdevwfm02.replgroup.com/retail/data/retailwebapi/api/v1
ConnectorSpecificSettingSiteManagerUrl   : https://nehstdevfas01.replgroup.com/retail/data/wfmsm/api/v1-beta2
DesignatedActorId                        : b862c9A7-416A-43aA-4Eac-db0C56eCDddC
EnabledConnectorScenario                 : {SwapRequest, OpenShiftRequest}
EnabledWfiScenario                       : {}
Etag                                     : "30013a2e-0000-0700-0000-60b4d1940000"
Id                                       : WCI-c4b4266e-769a-4403-a87d-563d26d3c7d9
Name                                     : Leo s Connector Instance
SyncFrequencyInMin                       : 10
TenantId                                 : b9a3c751-d652-47f0-b612-9dffc7a4e800
WorkforceIntegrationId                   : WFI_8dbddbb0-6cba-4861-a541-192320cc0e88

ConnectorId                              : 6A51B888-FF44-4FEA-82E1-839401E9CD74
ConnectorName                            : Blue Yonder
ConnectorSpecificSettingAdminApiUrl      : https://nehstdevwfm02.replgroup.com/retail/data/wfmadmin/api/v1-beta2
ConnectorSpecificSettingCookieAuthUrl    : https://nehstdevwfm02.replgroup.com/retail/data/login
ConnectorSpecificSettingEssApiUrl        : https://nehstdevfas01.replgroup.com/retail/data/wfmess/api/v1-beta1
ConnectorSpecificSettingFederatedAuthUrl : https://nehstdevfas01.replgroup.com/retail/data/login
ConnectorSpecificSettingRetailWebApiUrl  : https://nehstdevwfm02.replgroup.com/retail/data/retailwebapi/api/v1
ConnectorSpecificSettingSiteManagerUrl   : https://nehstdevfas01.replgroup.com/retail/data/wfmsm/api/v1-beta2
DesignatedActorId                        : 0c1141fa-1b17-43cc-a417-34c156b99779
EnabledConnectorScenario                 : {Shift, SwapRequest, UserShiftPreferences, OpenShift...}
EnabledWfiScenario                       : {Shift, SwapRequest, UserShiftPreferences, OpenShift...}
Etag                                     : "0000ce4b-0000-0700-0000-60b905b20000"
Id                                       : WCI-54d3d260-f171-4106-8f1d-3247a5b43486
Name                                     : Guchuan instantance3
SyncFrequencyInMin                       : 10
TenantId                                 : b9a3c751-d652-47f0-b612-9dffc7a4e800
WorkforceIntegrationId                   : WFI_8dbddbb0-6cba-4861-a541-192320cc0e88

ConnectorId                              : 6A51B888-FF44-4FEA-82E1-839401E9CD74
ConnectorName                            : Blue Yonder
ConnectorSpecificSettingAdminApiUrl      : https://nehstdevwfm02.replgroup.com/retail/data/wfmadmin/api/v1-beta2
ConnectorSpecificSettingCookieAuthUrl    : https://nehstdevwfm02.replgroup.com/retail/data/login
ConnectorSpecificSettingEssApiUrl        : https://nehstdevfas01.replgroup.com/retail/data/wfmess/api/v1-beta1
ConnectorSpecificSettingFederatedAuthUrl : https://nehstdevfas01.replgroup.com/retail/data/login
ConnectorSpecificSettingRetailWebApiUrl  : https://nehstdevwfm02.replgroup.com/retail/data/retailwebapi/api/v1
ConnectorSpecificSettingSiteManagerUrl   : https://nehstdevfas01.replgroup.com/retail/data/wfmsm/api/v1-beta2
DesignatedActorId                        : 0c1141fa-1b17-43cc-a417-34c156b99779
EnabledConnectorScenario                 : {Shift, SwapRequest, OpenShift, OpenShiftRequest...}
EnabledWfiScenario                       : {Shift, SwapRequest, OpenShift, OpenShiftRequest...}
Etag                                     : "0000605c-0000-0700-0000-60b94af20000"
Id                                       : WCI-85e864f2-3a75-43fa-ac3e-6ef571a3e5d9
Name                                     : Guchuan instance5
SyncFrequencyInMin                       : 10
TenantId                                 : b9a3c751-d652-47f0-b612-9dffc7a4e800
WorkforceIntegrationId                   : WFI_8dbddbb0-6cba-4861-a541-192320cc0e88

ConnectorId                              : 6A51B888-FF44-4FEA-82E1-839401E9CD74
ConnectorName                            : Blue Yonder
ConnectorSpecificSettingAdminApiUrl      : https://nehstdevwfm02.replgroup.com/retail/data/wfmadmin/api/v1-beta2
ConnectorSpecificSettingCookieAuthUrl    : https://nehstdevwfm02.replgroup.com/retail/data/login
ConnectorSpecificSettingEssApiUrl        : https://nehstdevfas01.replgroup.com/retail/data/wfmess/api/v1-beta1
ConnectorSpecificSettingFederatedAuthUrl : https://nehstdevfas01.replgroup.com/retail/data/login
ConnectorSpecificSettingRetailWebApiUrl  : https://nehstdevwfm02.replgroup.com/retail/data/retailwebapi/api/v1
ConnectorSpecificSettingSiteManagerUrl   : https://nehstdevfas01.replgroup.com/retail/data/wfmsm/api/v1-beta2
DesignatedActorId                        : 0c1141fa-1b17-43cc-a417-34c156b99779
EnabledConnectorScenario                 : {Shift, SwapRequest, OpenShift, OpenShiftRequest...}
EnabledWfiScenario                       : {Shift, SwapRequest, OpenShift, OpenShiftRequest...}
Etag                                     : "00009f5e-0000-0700-0000-60b951c10000"
Id                                       : WCI-d1addd70-2684-4723-b8f2-7fa2230648c9
Name                                     : Guchuan instance6
SyncFrequencyInMin                       : 10
TenantId                                 : b9a3c751-d652-47f0-b612-9dffc7a4e800
WorkforceIntegrationId                   : WFI_8dbddbb0-6cba-4861-a541-192320cc0e88

ConnectorId                              : 6A51B888-FF44-4FEA-82E1-839401E9CD74
ConnectorName                            : Blue Yonder
ConnectorSpecificSettingAdminApiUrl      : https://nehstdevwfm02.replgroup.com/retail/data/wfmadmin/api/v1-beta2
ConnectorSpecificSettingCookieAuthUrl    : https://nehstdevwfm02.replgroup.com/retail/data/login
ConnectorSpecificSettingEssApiUrl        : https://nehstdevfas01.replgroup.com/retail/data/wfmess/api/v1-beta1
ConnectorSpecificSettingFederatedAuthUrl : https://nehstdevfas01.replgroup.com/retail/data/login
ConnectorSpecificSettingRetailWebApiUrl  : https://nehstdevwfm02.replgroup.com/retail/data/retailwebapi/api/v1
ConnectorSpecificSettingSiteManagerUrl   : https://nehstdevfas01.replgroup.com/retail/data/wfmsm/api/v1-beta2
DesignatedActorId                        : 910ba867-3349-4bff-bc9f-6460ae8c9761
EnabledConnectorScenario                 : {Shift, OpenShift, TimeOff}
EnabledWfiScenario                       : {Shift, OpenShift, TimeOff}
Etag                                     : "0000a085-0000-0700-0000-60ba2cb50000"
Id                                       : WCI-6e4bd9f6-5617-4012-82eb-6dd51bf30bfa
Name                                     : Nialls Test Connector Instance
SyncFrequencyInMin                       : 180
TenantId                                 : b9a3c751-d652-47f0-b612-9dffc7a4e800
WorkforceIntegrationId                   : WFI_8dbddbb0-6cba-4861-a541-192320cc0e88

ConnectorId                              : 6A51B888-FF44-4FEA-82E1-839401E9CD74
ConnectorName                            : Blue Yonder
ConnectorSpecificSettingAdminApiUrl      : https://nehstdevwfm02.replgroup.com/retail/data/wfmadmin/api/v1-beta2
ConnectorSpecificSettingCookieAuthUrl    : https://nehstdevwfm02.replgroup.com/retail/data/login
ConnectorSpecificSettingEssApiUrl        : https://nehstdevfas01.replgroup.com/retail/data/wfmess/api/v1-beta1
ConnectorSpecificSettingFederatedAuthUrl : https://nehstdevfas01.replgroup.com/retail/data/login
ConnectorSpecificSettingRetailWebApiUrl  : https://nehstdevwfm02.replgroup.com/retail/data/retailwebapi/api/v1
ConnectorSpecificSettingSiteManagerUrl   : https://nehstdevfas01.replgroup.com/retail/data/wfmsm/api/v1-beta2
DesignatedActorId                        : 656c81a0-21cf-461c-ac83-07d0023bd62b
EnabledConnectorScenario                 : {Shift, SwapRequest, UserShiftPreferences, OpenShift...}
EnabledWfiScenario                       : {SwapRequest, OpenShift, OpenShiftRequest, OfferShiftRequest...}
Etag                                     : "0e00d46a-0000-0700-0000-60babcca0000"
Id                                       : WCI-2302814d-f316-4d80-91cc-11508c24d51c
Name                                     : Sushruth Instance
SyncFrequencyInMin                       : 20
TenantId                                 : b9a3c751-d652-47f0-b612-9dffc7a4e800
WorkforceIntegrationId                   : WFI_8dbddbb0-6cba-4861-a541-192320cc0e88

.Inputs
Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Models.IConfigApiBasedCmdletsIdentity
.Outputs
Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Models.IConnectorInstanceResponse
.Outputs
Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Models.IErrorDetailsResponse
.Notes
COMPLEX PARAMETER PROPERTIES

To create the parameters described below, construct a hash table containing the appropriate properties. For information on hash tables, run Get-Help about_Hash_Tables.

INPUTOBJECT <IConfigApiBasedCmdletsIdentity>: Identity Parameter
  [AppId <String>]: 
  [AudioFileId <String>]: 
  [Bssid <String>]: 
  [ChassisId <String>]: 
  [CivicAddressId <String>]: 
  [ConfigName <String>]: 
  [ConfigType <String>]: string
  [ConnectorInstanceId <String>]: Connector Instance Id
  [Country <String>]: 
  [DialedNumber <String>]: 
  [EndpointId <String>]: Application instance Id.
  [ErrorReportId <String>]: The UUID of a report instance
  [GroupId <String>]: The ID of a group whose policy assignments will be returned.
  [Id <String>]: 
  [Identity <String>]: 
  [Locale <String>]: 
  [LocationId <String>]: Location id.
  [MemberId <String>]: ObjectId of the to-be-added member.
  [OdataId <String>]: A composite URI of a template.
  [OperationId <String>]: The ID of a batch policy assignment operation.
  [OrderId <String>]: 
  [OwnerId <String>]: ObjectId of the group owner
  [PackageName <String>]: The name of a specific policy package
  [PolicyType <String>]: The policy type for which group policy assignments will be returned.
  [PortId <String>]: 
  [PublicTemplateLocale <String>]: Language and country code for localization of publicly available templates.
  [SubnetId <String>]: 
  [TeamId <String>]: Team Id
  [UserId <String>]: UserId. Supports Guid. Eventually UPN and SIP.
  [Version <String>]: 
  [WfmTeamId <String>]: Team Id
.Link
https://docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectioninstance
#>
function Get-CsTeamsShiftsConnectionInstance {
[OutputType([Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Models.IConnectorInstanceResponse], [Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Models.IErrorDetailsResponse])]
[CmdletBinding(DefaultParameterSetName='Get', PositionalBinding=$false)]
param(
    [Parameter(ParameterSetName='Get1', Mandatory)]
    [Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Category('Path')]
    [System.String]
    # Connector Instance Id
    ${ConnectorInstanceId},

    [Parameter(ParameterSetName='GetViaIdentity', Mandatory, ValueFromPipeline)]
    [Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Category('Path')]
    [Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Models.IConfigApiBasedCmdletsIdentity]
    # Identity Parameter
    # To construct, see NOTES section for INPUTOBJECT properties and create a hash table.
    ${InputObject},

    [Parameter(DontShow)]
    [Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Category('Runtime')]
    [System.Management.Automation.SwitchParameter]
    # Wait for .NET debugger to attach
    ${Break},

    [Parameter(DontShow)]
    [ValidateNotNull()]
    [Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Category('Runtime')]
    [Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Runtime.SendAsyncStep[]]
    # SendAsync Pipeline Steps to be appended to the front of the pipeline
    ${HttpPipelineAppend},

    [Parameter(DontShow)]
    [ValidateNotNull()]
    [Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Category('Runtime')]
    [Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Runtime.SendAsyncStep[]]
    # SendAsync Pipeline Steps to be prepended to the front of the pipeline
    ${HttpPipelinePrepend},

    [Parameter(DontShow)]
    [Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Category('Runtime')]
    [System.Uri]
    # The URI for the proxy server to use
    ${Proxy},

    [Parameter(DontShow)]
    [ValidateNotNull()]
    [Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Category('Runtime')]
    [System.Management.Automation.PSCredential]
    # Credentials for a proxy server to use for the remote call
    ${ProxyCredential},

    [Parameter(DontShow)]
    [Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Category('Runtime')]
    [System.Management.Automation.SwitchParameter]
    # Use the default credentials for the proxy
    ${ProxyUseDefaultCredentials}
)

begin {
    try {
        $outBuffer = $null
        if ($PSBoundParameters.TryGetValue('OutBuffer', [ref]$outBuffer)) {
            $PSBoundParameters['OutBuffer'] = 1
        }
        $parameterSet = $PSCmdlet.ParameterSetName
        $mapping = @{
            Get = 'Microsoft.Teams.ConfigAPI.Cmdlets.private\Get-CsTeamsShiftsConnectionInstance_Get';
            Get1 = 'Microsoft.Teams.ConfigAPI.Cmdlets.private\Get-CsTeamsShiftsConnectionInstance_Get1';
            GetViaIdentity = 'Microsoft.Teams.ConfigAPI.Cmdlets.private\Get-CsTeamsShiftsConnectionInstance_GetViaIdentity';
        }
        $cmdInfo = Get-Command -Name $mapping[$parameterSet]
        [Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Runtime.MessageAttributeHelper]::ProcessCustomAttributesAtRuntime($cmdInfo, $MyInvocation, $parameterSet, $PSCmdlet)
        $wrappedCmd = $ExecutionContext.InvokeCommand.GetCommand(($mapping[$parameterSet]), [System.Management.Automation.CommandTypes]::Cmdlet)
        $scriptCmd = {& $wrappedCmd @PSBoundParameters}
        $steppablePipeline = $scriptCmd.GetSteppablePipeline($MyInvocation.CommandOrigin)
        $steppablePipeline.Begin($PSCmdlet)
    } catch {
        throw
    }
}

process {
    try {
        $steppablePipeline.Process($_)
    } catch {
        throw
    }
}

end {
    try {
        $steppablePipeline.End()
    } catch {
        throw
    }
}
}

# SIG # Begin signature block
# MIIjbQYJKoZIhvcNAQcCoIIjXjCCI1oCAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCCUy9PFUUqMGL4i
# RnOEaENOL7LswewhANtdPbWnhXQ9+qCCDXMwggXxMIID2aADAgECAhMzAAACGYwK
# n7IWKxDmAAAAAAIZMA0GCSqGSIb3DQEBCwUAMH4xCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNpZ25p
# bmcgUENBIDIwMTEwHhcNMjEwNDI5MTkxMjU1WhcNMjIwNDI4MTkxMjU1WjByMQsw
# CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
# ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMRwwGgYDVQQDExNTa3lw
# ZSBTb2Z0d2FyZSBTYXJsMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
# nxMscK0w8ebaayvQhxPtLTkomfivSX4yNLmQJGXG+1yUKU4fmdQAhZm5mSIdFAEv
# sjAwCP3vUmh2N5R5TrAN/whfjGcDDlCYonKcrmuSaXxGuyjXKlELlRmPOaobqeo1
# 1Amcz6SRbNYBtKtRiP5ip2PfAvtJp7AvH0mZfGXKehE4C+5t8XYZ3K1JU3Tdb+3Z
# z+smovI8h/ZPe+uV2ORTxxa9kBLDvueJZbzKkn/WAIX/8rq/ywHtffSTXSueUmoe
# NJ0UCyoNBr90xtnozaCVknyRG8qWzHEZlc43FPNwIW6y8k1JSuspq+SML/HP7Fjv
# 7zcTLtM1HBBX/I9KxBJSBQIDAQABo4IBcjCCAW4wEwYDVR0lBAwwCgYIKwYBBQUH
# AwMwHQYDVR0OBBYEFAZqNYGuvWVnCVhV5aJBAvx4cJdwMFAGA1UdEQRJMEekRTBD
# MSkwJwYDVQQLEyBNaWNyb3NvZnQgT3BlcmF0aW9ucyBQdWVydG8gUmljbzEWMBQG
# A1UEBRMNMjMwMjU0KzQ2NDU2MjAfBgNVHSMEGDAWgBRIbmTlUAXTgqoXNzcitW2o
# ynUClTBUBgNVHR8ETTBLMEmgR6BFhkNodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20v
# cGtpb3BzL2NybC9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3JsMGEGCCsG
# AQUFBwEBBFUwUzBRBggrBgEFBQcwAoZFaHR0cDovL3d3dy5taWNyb3NvZnQuY29t
# L3BraW9wcy9jZXJ0cy9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3J0MAwG
# A1UdEwEB/wQCMAAwDQYJKoZIhvcNAQELBQADggIBABRKE3yDcJHa8xnyFn9Z+0m8
# vQLeUGC9933o78aSOWDkvcPFPczSqvw4cUmQnHPcRwDS1mwlYs5TmCdIS6Ij++Or
# uWxfgMdPRpveO6zT8rDWBL2sqCT/k5yCO75DVhT4kE/qEe81T4OY/Ejx3lZbBE1a
# z2k5dOL/ZWqNu8FdKSDmBZEeENOYy9UIyLf6coV2KLERB2IZ3W8U3z37fPA5nRMw
# +9sWWb98Gdm8exr4UwmnU0q8Y0KvJx/xwqOPShgiDjHsWev3fzsKSYzebkfBdLbw
# DZl9880mrGr03CfEWGDWa0tJui3LRh4csIuxWHkUrFw/R2N8baMDGPEUCh7dE+qf
# nuuMJ5tRUmnMOqyqj8dLXUZa+yxxpS91qde5asle0+WfzjLQ1D+T6ElhLBQU9LNh
# 5nhbD1+kJkVHFAU2tM3MXa2tgMVWFWQP4IqcQDWMW68M90VkGUrJ+t63oRO8HwbL
# 4IZJxG0wW/527ypSQTmpLSX6mM2vIyFHsO4zCvjDq8yfnDk25bpUNJbfOpqVkkWP
# UE+4bNIQbzcWgKgPIZDOka3pxq4vI05ns3tnvWS7TKiG+7ZYr5ZBSS6pr1Wykt0U
# aXxaUZuAWwikj2gvZAXR35f5bDg+36WoJTpQKNqzsY7dyL6SxkcZI8DcEKWEfbWd
# BX8q+w5hzEWqh7TrYJ93MIIHejCCBWKgAwIBAgIKYQ6Q0gAAAAAAAzANBgkqhkiG
# 9w0BAQsFADCBiDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAO
# BgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEy
# MDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2VydGlmaWNhdGUgQXV0aG9yaXR5IDIw
# MTEwHhcNMTEwNzA4MjA1OTA5WhcNMjYwNzA4MjEwOTA5WjB+MQswCQYDVQQGEwJV
# UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UE
# ChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQgQ29k
# ZSBTaWduaW5nIFBDQSAyMDExMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKC
# AgEAq/D6chAcLq3YbqqCEE00uvK2WCGfQhsqa+laUKq4BjgaBEm6f8MMHt03a8YS
# 2AvwOMKZBrDIOdUBFDFC04kNeWSHfpRgJGyvnkmc6Whe0t+bU7IKLMOv2akrrnoJ
# r9eWWcpgGgXpZnboMlImEi/nqwhQz7NEt13YxC4Ddato88tt8zpcoRb0RrrgOGSs
# bmQ1eKagYw8t00CT+OPeBw3VXHmlSSnnDb6gE3e+lD3v++MrWhAfTVYoonpy4BI6
# t0le2O3tQ5GD2Xuye4Yb2T6xjF3oiU+EGvKhL1nkkDstrjNYxbc+/jLTswM9sbKv
# kjh+0p2ALPVOVpEhNSXDOW5kf1O6nA+tGSOEy/S6A4aN91/w0FK/jJSHvMAhdCVf
# GCi2zCcoOCWYOUo2z3yxkq4cI6epZuxhH2rhKEmdX4jiJV3TIUs+UsS1Vz8kA/DR
# elsv1SPjcF0PUUZ3s/gA4bysAoJf28AVs70b1FVL5zmhD+kjSbwYuER8ReTBw3J6
# 4HLnJN+/RpnF78IcV9uDjexNSTCnq47f7Fufr/zdsGbiwZeBe+3W7UvnSSmnEyim
# p31ngOaKYnhfsi+E11ecXL93KCjx7W3DKI8sj0A3T8HhhUSJxAlMxdSlQy90lfdu
# +HggWCwTXWCVmj5PM4TasIgX3p5O9JawvEagbJjS4NaIjAsCAwEAAaOCAe0wggHp
# MBAGCSsGAQQBgjcVAQQDAgEAMB0GA1UdDgQWBBRIbmTlUAXTgqoXNzcitW2oynUC
# lTAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTALBgNVHQ8EBAMCAYYwDwYDVR0T
# AQH/BAUwAwEB/zAfBgNVHSMEGDAWgBRyLToCMZBDuRQFTuHqp8cx0SOJNDBaBgNV
# HR8EUzBRME+gTaBLhklodHRwOi8vY3JsLm1pY3Jvc29mdC5jb20vcGtpL2NybC9w
# cm9kdWN0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3JsMF4GCCsGAQUF
# BwEBBFIwUDBOBggrBgEFBQcwAoZCaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3Br
# aS9jZXJ0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3J0MIGfBgNVHSAE
# gZcwgZQwgZEGCSsGAQQBgjcuAzCBgzA/BggrBgEFBQcCARYzaHR0cDovL3d3dy5t
# aWNyb3NvZnQuY29tL3BraW9wcy9kb2NzL3ByaW1hcnljcHMuaHRtMEAGCCsGAQUF
# BwICMDQeMiAdAEwAZQBnAGEAbABfAHAAbwBsAGkAYwB5AF8AcwB0AGEAdABlAG0A
# ZQBuAHQALiAdMA0GCSqGSIb3DQEBCwUAA4ICAQBn8oalmOBUeRou09h0ZyKbC5YR
# 4WOSmUKWfdJ5DJDBZV8uLD74w3LRbYP+vj/oCso7v0epo/Np22O/IjWll11lhJB9
# i0ZQVdgMknzSGksc8zxCi1LQsP1r4z4HLimb5j0bpdS1HXeUOeLpZMlEPXh6I/MT
# faaQdION9MsmAkYqwooQu6SpBQyb7Wj6aC6VoCo/KmtYSWMfCWluWpiW5IP0wI/z
# Rive/DvQvTXvbiWu5a8n7dDd8w6vmSiXmE0OPQvyCInWH8MyGOLwxS3OW560STkK
# xgrCxq2u5bLZ2xWIUUVYODJxJxp/sfQn+N4sOiBpmLJZiWhub6e3dMNABQamASoo
# PoI/E01mC8CzTfXhj38cbxV9Rad25UAqZaPDXVJihsMdYzaXht/a8/jyFqGaJ+HN
# pZfQ7l1jQeNbB5yHPgZ3BtEGsXUfFL5hYbXw3MYbBL7fQccOKO7eZS/sl/ahXJbY
# ANahRr1Z85elCUtIEJmAH9AAKcWxm6U/RXceNcbSoqKfenoi+kiVH6v7RyOA9Z74
# v2u3S5fi63V4GuzqN5l5GEv/1rMjaHXmr/r8i+sLgOppO6/8MO0ETI7f33VtY5E9
# 0Z1WTk+/gFcioXgRMiF670EKsT/7qMykXcGhiJtXcVZOSEXAQsmbdlsKgEhr/Xmf
# wb1tbWrJUnMTDXpQzTGCFVAwghVMAgEBMIGVMH4xCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNpZ25p
# bmcgUENBIDIwMTECEzMAAAIZjAqfshYrEOYAAAAAAhkwDQYJYIZIAWUDBAIBBQCg
# gaYwGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEOMAwG
# CisGAQQBgjcCARUwLwYJKoZIhvcNAQkEMSIEIEJN+yUn8iIVsz/8J72v5vCJcSQh
# EEWWa1vpBxGYIQLTMDoGCisGAQQBgjcCAQwxLDAqoAyACgBTAGsAeQBwAGWhGoAY
# aHR0cDovL3d3dy5taWNyb3NvZnQuY29tMA0GCSqGSIb3DQEBAQUABIIBAJ5Xg/4H
# HR1G2eoBdjtl567W+Y1oiLoLLhFe5qnWN2+NGLatvqZBOqY4Vv70lUuP42juLZR5
# QWS38IdAODvutc/vuIrO+RePkfW3nvXdagDvmdwwHPMZgQlPSXaKwgvBZNTKhM7F
# 6TlYM+FoxLRL/hHBYuKSQkRfJHKesoWdrsnnTIx1ARymZibGQga8xWKO/9BBkE9O
# tziFuuT0f25avF0GBP06v/P+5tr2TEwUMAufxDXzgu7A93L4tX25yngY8RT+OLN3
# phlwoZ+a95cWNZMHrYNM4RVbOu5o/R6V8fYYFYAdF5O/cCEOWCOB9QTzcUKhdE4j
# EtoObeDwzVTimmuhghLiMIIS3gYKKwYBBAGCNwMDATGCEs4wghLKBgkqhkiG9w0B
# BwKgghK7MIIStwIBAzEPMA0GCWCGSAFlAwQCAQUAMIIBUQYLKoZIhvcNAQkQAQSg
# ggFABIIBPDCCATgCAQEGCisGAQQBhFkKAwEwMTANBglghkgBZQMEAgEFAAQgrZbD
# Rp1yZzsdvaSccjhtYwDThUhwNgyXNeaISIxD2E4CBmHlpN2/NhgTMjAyMjAxMjEw
# ODQzMzkuNTg2WjAEgAIB9KCB0KSBzTCByjELMAkGA1UEBhMCVVMxEzARBgNVBAgT
# Cldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
# dCBDb3Jwb3JhdGlvbjElMCMGA1UECxMcTWljcm9zb2Z0IEFtZXJpY2EgT3BlcmF0
# aW9uczEmMCQGA1UECxMdVGhhbGVzIFRTUyBFU046MjI2NC1FMzNFLTc4MEMxJTAj
# BgNVBAMTHE1pY3Jvc29mdCBUaW1lLVN0YW1wIFNlcnZpY2Wggg45MIIE8TCCA9mg
# AwIBAgITMwAAAUqk9zHE/yKiSQAAAAABSjANBgkqhkiG9w0BAQsFADB8MQswCQYD
# VQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEe
# MBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQDEx1NaWNyb3Nv
# ZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDAeFw0yMDExMTIxODI1NThaFw0yMjAyMTEx
# ODI1NThaMIHKMQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4G
# A1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSUw
# IwYDVQQLExxNaWNyb3NvZnQgQW1lcmljYSBPcGVyYXRpb25zMSYwJAYDVQQLEx1U
# aGFsZXMgVFNTIEVTTjoyMjY0LUUzM0UtNzgwQzElMCMGA1UEAxMcTWljcm9zb2Z0
# IFRpbWUtU3RhbXAgU2VydmljZTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
# ggEBAN7KKGZkolgsvVEaNKMTVZZgEl8ohsLgHR4gUFWLZvWzLbegDoRItpfFd+9m
# aW2hPFlgT+wv7lxf6OB4HFYZgHfIpcZhGU6/ebsymXYAmAKzKph71pxJU5F228YT
# STLcoSAIUNBZVdTEIZILEPT5gI77Ysu7YKMufSmiZPzqYlkEX2/dHhOcoo90zgIJ
# RTG1u2kF7w6a7D50yHKE46eGEwqwjExERCCNtFBDQrTfYID/Icj0zKikYjiJRaaP
# NjnvBaRJ/eFkGz8gD2XyYXjlsNjDGPaGPQTt/Rm3nrxcyXGyCIIhWdBMXMTLl7BM
# DKKeLBQ0d6pFfS1LRJo+paKKBiUCAwEAAaOCARswggEXMB0GA1UdDgQWBBRxjGEY
# MfrAhjWKk/99frgmKqk/4TAfBgNVHSMEGDAWgBTVYzpcijGQ80N7fEYbxTNoWoVt
# VTBWBgNVHR8ETzBNMEugSaBHhkVodHRwOi8vY3JsLm1pY3Jvc29mdC5jb20vcGtp
# L2NybC9wcm9kdWN0cy9NaWNUaW1TdGFQQ0FfMjAxMC0wNy0wMS5jcmwwWgYIKwYB
# BQUHAQEETjBMMEoGCCsGAQUFBzAChj5odHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20v
# cGtpL2NlcnRzL01pY1RpbVN0YVBDQV8yMDEwLTA3LTAxLmNydDAMBgNVHRMBAf8E
# AjAAMBMGA1UdJQQMMAoGCCsGAQUFBwMIMA0GCSqGSIb3DQEBCwUAA4IBAQBRC67d
# RjgFFS9kv72Vfe8gQ+Hg3FpX2TYyOq4nrtPq9D36Udydr2ibZy5n7LphXvW20bDT
# ugUHiwuyfWnmyc2oEevo+SrNCzxXcj59Wv9lQpBgtL6OM56x+v1zbNzp/moMwk3U
# vysE5af5rktfFtPx6apqcjU1IDt09hX80ZAzqPflPPyC5Cj3J8DQilQz2/TzSZvc
# bgCM9vuwLu9p9bZhJemNP++3LrHkdycfHZf3jv7QBAigEvyVb2mrnlomFIKCyJW1
# cOrBjIqyntQt5PK8zKxX/yZlyiRbr8c0DQw8tYpXeyorgoVet9sAF+t3g/cYzVog
# W4qwhuyZmEmTlTSKMIIGcTCCBFmgAwIBAgIKYQmBKgAAAAAAAjANBgkqhkiG9w0B
# AQsFADCBiDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNV
# BAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEyMDAG
# A1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2VydGlmaWNhdGUgQXV0aG9yaXR5IDIwMTAw
# HhcNMTAwNzAxMjEzNjU1WhcNMjUwNzAxMjE0NjU1WjB8MQswCQYDVQQGEwJVUzET
# MBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMV
# TWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQDEx1NaWNyb3NvZnQgVGltZS1T
# dGFtcCBQQ0EgMjAxMDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKkd
# Dbx3EYo6IOz8E5f1+n9plGt0VBDVpQoAgoX77XxoSyxfxcPlYcJ2tz5mK1vwFVMn
# BDEfQRsalR3OCROOfGEwWbEwRA/xYIiEVEMM1024OAizQt2TrNZzMFcmgqNFDdDq
# 9UeBzb8kYDJYYEbyWEeGMoQedGFnkV+BVLHPk0ySwcSmXdFhE24oxhr5hoC732H8
# RsEnHSRnEnIaIYqvS2SJUGKxXf13Hz3wV3WsvYpCTUBR0Q+cBj5nf/VmwAOWRH7v
# 0Ev9buWayrGo8noqCjHw2k4GkbaICDXoeByw6ZnNPOcvRLqn9NxkvaQBwSAJk3jN
# /LzAyURdXhacAQVPIk0CAwEAAaOCAeYwggHiMBAGCSsGAQQBgjcVAQQDAgEAMB0G
# A1UdDgQWBBTVYzpcijGQ80N7fEYbxTNoWoVtVTAZBgkrBgEEAYI3FAIEDB4KAFMA
# dQBiAEMAQTALBgNVHQ8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAW
# gBTV9lbLj+iiXGJo0T2UkFvXzpoYxDBWBgNVHR8ETzBNMEugSaBHhkVodHRwOi8v
# Y3JsLm1pY3Jvc29mdC5jb20vcGtpL2NybC9wcm9kdWN0cy9NaWNSb29DZXJBdXRf
# MjAxMC0wNi0yMy5jcmwwWgYIKwYBBQUHAQEETjBMMEoGCCsGAQUFBzAChj5odHRw
# Oi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpL2NlcnRzL01pY1Jvb0NlckF1dF8yMDEw
# LTA2LTIzLmNydDCBoAYDVR0gAQH/BIGVMIGSMIGPBgkrBgEEAYI3LgMwgYEwPQYI
# KwYBBQUHAgEWMWh0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9QS0kvZG9jcy9DUFMv
# ZGVmYXVsdC5odG0wQAYIKwYBBQUHAgIwNB4yIB0ATABlAGcAYQBsAF8AUABvAGwA
# aQBjAHkAXwBTAHQAYQB0AGUAbQBlAG4AdAAuIB0wDQYJKoZIhvcNAQELBQADggIB
# AAfmiFEN4sbgmD+BcQM9naOhIW+z66bM9TG+zwXiqf76V20ZMLPCxWbJat/15/B4
# vceoniXj+bzta1RXCCtRgkQS+7lTjMz0YBKKdsxAQEGb3FwX/1z5Xhc1mCRWS3Tv
# QhDIr79/xn/yN31aPxzymXlKkVIArzgPF/UveYFl2am1a+THzvbKegBvSzBEJCI8
# z+0DpZaPWSm8tv0E4XCfMkon/VWvL/625Y4zu2JfmttXQOnxzplmkIz/amJ/3cVK
# C5Em4jnsGUpxY517IW3DnKOiPPp/fZZqkHimbdLhnPkd/DjYlPTGpQqWhqS9nhqu
# BEKDuLWAmyI4ILUl5WTs9/S/fmNZJQ96LjlXdqJxqgaKD4kWumGnEcua2A5HmoDF
# 0M2n0O99g/DhO3EJ3110mCIIYdqwUB5vvfHhAN/nMQekkzr3ZUd46PioSKv33nJ+
# YWtvd6mBy6cJrDm77MbL2IK0cs0d9LiFAR6A+xuJKlQ5slvayA1VmXqHczsI5pgt
# 6o3gMy4SKfXAL1QnIffIrE7aKLixqduWsqdCosnPGUFN4Ib5KpqjEWYw07t0Mkvf
# Y3v1mYovG8chr1m1rtxEPJdQcdeh0sVV42neV8HR3jDA/czmTfsNv11P6Z0eGTgv
# vM9YBS7vDaBQNdrvCScc1bN+NR4Iuto229Nfj950iEkSoYICyzCCAjQCAQEwgfih
# gdCkgc0wgcoxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYD
# VQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJTAj
# BgNVBAsTHE1pY3Jvc29mdCBBbWVyaWNhIE9wZXJhdGlvbnMxJjAkBgNVBAsTHVRo
# YWxlcyBUU1MgRVNOOjIyNjQtRTMzRS03ODBDMSUwIwYDVQQDExxNaWNyb3NvZnQg
# VGltZS1TdGFtcCBTZXJ2aWNloiMKAQEwBwYFKw4DAhoDFQC8BO6GhSDKwTN3KQTV
# tEHiiHprmKCBgzCBgKR+MHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5n
# dG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9y
# YXRpb24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwMA0G
# CSqGSIb3DQEBBQUAAgUA5ZTAbjAiGA8yMDIyMDEyMTEzMTczNFoYDzIwMjIwMTIy
# MTMxNzM0WjB0MDoGCisGAQQBhFkKBAExLDAqMAoCBQDllMBuAgEAMAcCAQACAgLV
# MAcCAQACAhGhMAoCBQDllhHuAgEAMDYGCisGAQQBhFkKBAIxKDAmMAwGCisGAQQB
# hFkKAwKgCjAIAgEAAgMHoSChCjAIAgEAAgMBhqAwDQYJKoZIhvcNAQEFBQADgYEA
# TfHg+6zDnPNt9DB1285+nSsz9Q2Dkil4DxBrUzV29KCoDxQYF5LaFOSF8f+fzYbU
# 7NELYbM33x25zBfrkjWA3rYaQEwUvoC38MsdNzEMU7GFRAnSmHtCg2gKej8U2HR4
# 0TrxRYoojycqKG/VpIMxwZkKDVHReyrzxzSfjlY2QjwxggMNMIIDCQIBATCBkzB8
# MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVk
# bW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQDEx1N
# aWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMAITMwAAAUqk9zHE/yKiSQAAAAAB
# SjANBglghkgBZQMEAgEFAKCCAUowGgYJKoZIhvcNAQkDMQ0GCyqGSIb3DQEJEAEE
# MC8GCSqGSIb3DQEJBDEiBCAgCW9MBA/qPSf8s+0B2RQJ3wF2e0SKP7k8x9r9ccJW
# nDCB+gYLKoZIhvcNAQkQAi8xgeowgecwgeQwgb0EIGwdktetudtX/kn7Yq/AVYiB
# WZBq+n4EFVQ8zUD3IlEDMIGYMIGApH4wfDELMAkGA1UEBhMCVVMxEzARBgNVBAgT
# Cldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
# dCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENB
# IDIwMTACEzMAAAFKpPcxxP8iokkAAAAAAUowIgQgDWvjJFpJYBoBsZ1cIJHKpj0i
# 4YTycdUpZFEpVCph3BUwDQYJKoZIhvcNAQELBQAEggEAuSsr/I4KZGZMu98f6XrE
# VEMr+vLdbpJkx3pR+kw8d5ifPqQtr4tSn0JI2ra28g5a4FG0xhSnyOOhglI0aS0p
# Fz6hZD3T+mtFQeP+R16b1lXxeYJCcgCmcBAfZhGvnsPm3FLO2vChuaV3zB+oO5dl
# Kaxyiub2V5vUP86AQwa/dIgtJirjbwdShOPSgRFky+cyWhmSS+hyQn2RpUPs6viU
# 7mrw68fX2NeBHRS9DysTjm76kefM8sAMAeTgRSlWYIoS30qJSB0/n43tTy4wEr4G
# xsvHBPsGl3m7cR75n67G3SkTYGwtlU5yI/k8rEgzNEGclMzB1Bxff67IkHEwMSG3
# 6g==
# SIG # End signature block
