#
# Module manifest for module 'MicrosoftTeams'
#
# Generated by: Microsoft Corporation
#
# Updated on: 6/30/2020
#

@{
# Script module or binary module file associated with this manifest.
RootModule = './MicrosoftTeams.psm1'

# Version number of this module.
ModuleVersion = '3.1.0'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = 'd910df43-3ca6-4c9c-a2e3-e9f45a8e2ad9'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = 'Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Microsoft Teams cmdlets module for Windows PowerShell and PowerShell Core.

For more information, please visit the following: https://docs.microsoft.com/MicrosoftTeams/teams-powershell-overview'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
CLRVersion = '4.0'

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = 'Amd64'

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# Removed this script from here because this module is used in SAW machines as well where Contraint Language Mode is on.
# Because of CLM constraint we were not able to import Teams module to SAW machines, that is why removing this script.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = if($PSEdition -ne 'Desktop')
{
    '.\netcoreapp3.1\Microsoft.TeamsCmdlets.PowerShell.Connect.dll',
    '.\netcoreapp3.1\Microsoft.Teams.ConfigAPI.Cmdlets.psd1',
    '.\Microsoft.Teams.PowerShell.TeamsCmdlets.psd1'
}
else
{
    '.\net472\Microsoft.TeamsCmdlets.PowerShell.Connect.dll',
    '.\net472\Newtonsoft.Json.dll',
    '.\net472\Microsoft.Teams.ConfigAPI.Cmdlets.psd1',
    '.\Microsoft.Teams.PowerShell.TeamsCmdlets.psd1'
}

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport =  @(
   'Get-CsBatchPolicyAssignmentOperation'
   ,'Get-CsGroupPolicyAssignment'
   ,'Get-CsOnlinePowerShellEndpoint'
   ,'Get-CsPolicyPackage'
   ,'Get-CsUserPolicyAssignment'
   ,'Get-CsUserPolicyPackage'
   ,'Get-CsUserPolicyPackageRecommendation'
   ,'Grant-CsUserPolicyPackage'
   ,'New-CsBatchPolicyAssignmentOperation'
   ,'New-CsBatchPolicyPackageAssignmentOperation'
   ,'New-CsGroupPolicyAssignment'
   ,'Remove-CsGroupPolicyAssignment'
   ,'Move-CsInternalHelper'
   ,'Set-CsInternalOnlinePowerShellEndpoint'
   ,'Invoke-CsInternalPSTelemetry'
   ,'Grant-CsGroupPolicyPackageAssignment'
   ,'Get-CsTeamTemplateList'
   ,'Get-CsTeamTemplate'
   ,'Update-CsTeamTemplate'
   ,'New-CsTeamTemplate'
   ,'Remove-CsTeamTemplate'
   ,'New-CsCustomPolicyPackage'
   ,'Update-CsCustomPolicyPackage'
   ,'Remove-CsCustomPolicyPackage'
#Skype.TelephoneNumberMgmt Search V2
   ,'Get-CsOnlineTelephoneNumberCountry'
   ,'Get-CsOnlineTelephoneNumberType'
   ,'Get-CsOnlineTelephoneNumberOrder'
   ,'New-CsOnlineTelephoneNumberOrder'
   ,'Complete-CsOnlineTelephoneNumberOrder'
   ,'Clear-CsOnlineTelephoneNumberOrder'
#Skype.TelephoneNumberMgmt PhoneNumberAssignment
   ,'Set-CsPhoneNumberAssignment'
   ,'Remove-CsPhoneNumberAssignment'
#Audio File (autorest only)
   ,'Get-CsOnlineAudioFile'
   ,'Remove-CsOnlineAudioFile'
   ,'Export-CsOnlineAudioFile'
#Shifts Connector: Begin
#preview    ,'Get-CsTeamsShiftsConnectionConnector'
#preview    ,'Test-CsTeamsShiftsConnectionValidate'
#preview    ,'New-CsTeamsShiftsConnectionInstance'
#preview    ,'Set-CsTeamsShiftsConnectionInstance'
#preview    ,'Remove-CsTeamsShiftsConnectionInstance'
#preview    ,'Get-CsTeamsShiftsConnectionInstance'
#preview    ,'Get-CsTeamsShiftsConnectionWfmTeam'
#preview    ,'New-CsTeamsShiftsConnectionTeamMap'
#preview    ,'Remove-CsTeamsShiftsConnectionTeamMap'
#preview    ,'Get-CsTeamsShiftsConnectionTeamMap'
#preview    ,'Get-CsTeamsShiftsConnectionSyncResult'
#preview    ,'Get-CsTeamsShiftsConnectionWfmUser'
#preview    ,'Get-CsTeamsShiftsConnectionOperation'
#preview    ,'New-CsTeamsShiftsConnectionBatchTeamMap'
#preview    ,'Remove-CsTeamsShiftsScheduleRecord'
#preview    ,'Get-CsTeamsShiftsConnectionErrorReport'
#preview    ,'Disable-CsTeamsShiftsConnectionErrorReport'
#Shifts Connector: End
#preview    ,'Get-CsUserCallingSettings'
#preview    ,'Set-CsUserCallingSettings'
#preview    ,'New-CsUserCallingDelegate'
#preview    ,'Set-CsUserCallingDelegate'
#preview    ,'Remove-CsUserCallingDelegate'
#SfBO: Begin
   ,'Clear-CsOnlineTelephoneNumberReservation'
   ,'ConvertTo-JsonForPSWS'
   ,'Disable-CsMeetingRoom'
   ,'Disable-CsOnlineDialInConferencingUser'
   ,'Disable-CsOnlineSipDomain'
   ,'Enable-CsMeetingRoom'
   ,'Enable-CsOnlineDialInConferencingUser'
   ,'Enable-CsOnlineSipDomain'
   ,'Export-CsAutoAttendantHolidays'
   ,'Find-CsGroup'
   ,'Find-CsOnlineApplicationInstance'
   ,'Get-CsApplicationAccessPolicy'
   ,'Get-CsApplicationMeetingConfiguration'
   ,'Get-CsAudioConferencingProvider'
   ,'Get-CsAutoAttendant'
   ,'Get-CsAutoAttendantHolidays'
   ,'Get-CsAutoAttendantStatus'
   ,'Get-CsAutoAttendantSupportedLanguage'
   ,'Get-CsAutoAttendantSupportedTimeZone'
   ,'Get-CsAutoAttendantTenantInformation'
   ,'Get-CsBroadcastMeetingConfiguration'
   ,'Get-CsBroadcastMeetingPolicy'
   ,'Get-CsCallingLineIdentity'
   ,'Get-CsCallQueue'
   ,'Get-CsClientPolicy'
   ,'Get-CsCloudCallDataConnection'
   ,'Get-CsCloudMeetingPolicy'
   ,'Get-CsConferencingPolicy'
   ,'Get-CsDefaultCatalogApp'
   ,'Get-CsDialPlan'
   ,'Get-CsEffectiveTenantDialPlan'
   ,'Get-CsExternalAccessPolicy'
   ,'Get-CsExternalUserCommunicationPolicy'
   ,'Get-CsGlobalCatalogApp'
   ,'Get-CsGraphPolicy'
   ,'Get-CsHostedVoicemailPolicy'
   ,'Get-CsHostingProvider'
   ,'Get-CsHybridMediationServer'
   ,'Get-CsHybridPSTNAppliance'
   ,'Get-CsHybridPSTNSite'
   ,'Get-CsImFilterConfiguration'
   ,'Get-CsInboundBlockedNumberPattern'
   ,'Get-CsInboundExemptNumberPattern'
   ,'Get-CsIPPhonePolicy'
   ,'Get-CsMeetingConfiguration'
   ,'Get-CsMeetingMigrationStatus'
   ,'Get-CsMeetingRoom'
   ,'Get-CsMobilityPolicy'
   ,'Get-CsNetworkConfiguration'
   ,'Get-CsOAuthConfiguration'
   ,'Get-CsOnlineApplicationEndpoint'
   ,'Get-CsOnlineApplicationInstance'
   ,'Get-CsOnlineApplicationInstanceAssociation'
   ,'Get-CsOnlineApplicationInstanceAssociationStatus'
   ,'Get-CsOnlineAudioConferencingRoutingPolicy'
   ,'Get-CsOnlineDialInConferencingBridge'
   ,'Get-CsOnlineDialInConferencingLanguagesSupported'
   ,'Get-CsOnlineDialinConferencingPolicy'
   ,'Get-CsOnlineDialInConferencingServiceNumber'
   ,'Get-CsOnlineDialinConferencingTenantConfiguration'
   ,'Get-CsOnlineDialInConferencingTenantSettings'
   ,'Get-CsOnlineDialInConferencingUser'
   ,'Get-CsOnlineDialInConferencingUserInfo'
   ,'Get-CsOnlineDialInConferencingUserState'
   ,'Get-CsOnlineDialOutPolicy'
   ,'Get-CsOnlineDirectoryTenant'
   ,'Get-CsOnlineDirectoryTenantNumberCities'
   ,'Get-CsOnlineEnhancedEmergencyServiceDisclaimer'
   ,'Get-CsOnlineLisCivicAddress'
   ,'Get-CsOnlineLisLocation'
   ,'Get-CsOnlineLisPort'
   ,'Get-CsOnlineLisSubnet'
   ,'Get-CsOnlineLisSwitch'
   ,'Get-CsOnlineLisWirelessAccessPoint'
   ,'Get-CsOnlineNumberPortInOrder'
   ,'Get-CsOnlineNumberPortOutOrderPin'
   ,'Get-CsOnlinePSTNGateway'
   ,'Get-CsOnlinePstnUsage'
   ,'Get-CsOnlineSchedule'
   ,'Get-CsOnlineSipDomain'
   ,'Get-CsOnlineTelephoneNumber'
   ,'Get-CsOnlineTelephoneNumberAvailableCount'
   ,'Get-CsOnlineTelephoneNumberInventoryAreas'
   ,'Get-CsOnlineTelephoneNumberInventoryCities'
   ,'Get-CsOnlineTelephoneNumberInventoryCountries'
   ,'Get-CsOnlineTelephoneNumberInventoryRegions'
   ,'Get-CsOnlineTelephoneNumberInventoryTypes'
   ,'Get-CsOnlineTelephoneNumberReservationsInformation'
   ,'Get-CsOnlineUser'
   ,'Get-CsOnlineVoicemailPolicy'
   ,'Get-CsOnlineVoicemailUserSettings'
   ,'Get-CsOnlineVoiceRoute'
   ,'Get-CsOnlineVoiceRoutingPolicy'
   ,'Get-CsOnlineVoiceUser'
   ,'Get-CsPrivacyConfiguration'
   ,'Get-CsPushNotificationConfiguration'
   ,'Get-CsTeamsAcsFederationConfiguration'
   ,'Get-CsTeamsAppPermissionPolicy'
   ,'Get-CsTeamsAppPreset'
   ,'Get-CsTeamsAppSetupPolicy'
   ,'Get-CsTeamsAudioConferencingPolicy'
   ,'Get-CsTeamsCallingPolicy'
   ,'Get-CsTeamsCallParkPolicy'
   ,'Get-CsTeamsCallHoldPolicy'
   ,'Get-CsTeamsChannelsPolicy'
   ,'Get-CsTeamsClientConfiguration'
   ,'Get-CsTeamsComplianceRecordingApplication'
   ,'Get-CsTeamsComplianceRecordingPolicy'
   ,'Get-CsTeamsCortanaPolicy'
   ,'Get-CsTeamsEducationAssignmentsAppPolicy'
   ,'Get-CsTeamsEmergencyCallingPolicy'
   ,'Get-CsTeamsEmergencyCallRoutingPolicy'
   ,'Get-CsTeamsFeedbackPolicy'
   ,'Get-CsTeamsGuestCallingConfiguration'
   ,'Get-CsTeamsGuestMeetingConfiguration'
   ,'Get-CsTeamsGuestMessagingConfiguration'
   ,'Get-CsTeamsIPPhonePolicy'
   ,'Get-CsTeamsMeetingBroadcastConfiguration'
   ,'Get-CsTeamsMeetingBroadcastPolicy'
   ,'Get-CsTeamsMeetingConfiguration'
   ,'Get-CsTeamsMeetingPolicy'
   ,'Get-CsTeamsMessagingPolicy'
   ,'Get-CsTeamsMigrationConfiguration'
   ,'Get-CsTeamsMobilityPolicy'
   ,'Get-CsTeamsNetworkRoamingPolicy'
   ,'Get-CsTeamsNotificationAndFeedsPolicy'
   ,'Get-CsTeamsPinnedApp'
   ,'Get-CsTeamsShiftsAppPolicy'
   ,'Get-CsTeamsShiftsPolicy'
   ,'Get-CsTeamsSurvivableBranchAppliance'
   ,'Get-CsTeamsSurvivableBranchAppliancePolicy'
   ,'Get-CsTeamsTargetingPolicy'
   ,'Get-CsTeamsTranslationRule'
   ,'Get-CsTeamsUpdateManagementPolicy'
   ,'Get-CsTeamsUpgradeConfiguration'
   ,'Get-CsTeamsUpgradePolicy'
   ,'Get-CsTeamsUpgradeStatus'
   ,'Get-CsTeamsVdiPolicy'
   ,'Get-CsTeamsVerticalPackagePolicy'
   ,'Get-CsTeamsVideoInteropServicePolicy'
   ,'Get-CsTeamsWorkLoadPolicy'
   ,'Get-CsTenant'
   ,'Get-CsTenantBlockedCallingNumbers'
   ,'Get-CsTeamsEnhancedEncryptionPolicy'
   ,'Get-CsTenantCatalogApp'
   ,'Get-CsTenantDialPlan'
   ,'Get-CsTenantFederationConfiguration'
   ,'Get-CsTenantHybridConfiguration'
   ,'Get-CsTenantLicensingConfiguration'
   ,'Get-CsTenantMigrationConfiguration'
   ,'Get-CsTenantNetworkConfiguration'
   ,'Get-CsTenantNetworkPostalCode'
   ,'Get-CsTenantNetworkRegion'
   ,'Get-CsTenantNetworkSite'
   ,'Get-CsTenantNetworkSubnet'
   ,'Get-CsTenantPublicProvider'
   ,'Get-CsTenantTrustedIPAddress'
   ,'Get-CsTenantUpdateTimeWindow'
   ,'Get-CsUCPhoneConfiguration'
   ,'Get-CsUserLocationStatus'
   ,'Get-CsUserPstnSettings'
   ,'Get-CsUserServicesPolicy'
   ,'Get-CsVideoInteropServiceProvider'
   ,'Get-CsVoiceNormalizationRule'
   ,'Get-CsVoiceRoutingPolicy'
   ,'Get-CsTeamsUnassignedNumberTreatment'
   ,'Get-CsTeamsFilesPolicy'
   ,'Grant-CsApplicationAccessPolicy'
   ,'Grant-CsBroadcastMeetingPolicy'
   ,'Grant-CsCallingLineIdentity'
   ,'Grant-CsClientPolicy'
   ,'Grant-CsCloudMeetingPolicy'
   ,'Grant-CsConferencingPolicy'
   ,'Grant-CsDialoutPolicy'
   ,'Grant-CsExternalAccessPolicy'
   ,'Grant-CsExternalUserCommunicationPolicy'
   ,'Grant-CsGraphPolicy'
   ,'Grant-CsHostedVoicemailPolicy'
   ,'Grant-CsIPPhonePolicy'
   ,'Grant-CsMobilityPolicy'
   ,'Grant-CsOnlineAudioConferencingRoutingPolicy'
   ,'Grant-CsOnlineVoicemailPolicy'
   ,'Grant-CsOnlineVoiceRoutingPolicy'
   ,'Grant-CsPolicy'
   ,'Grant-CsTeamsAppPermissionPolicy'
   ,'Grant-CsTeamsAppSetupPolicy'
   ,'Grant-CsTeamsAudioConferencingPolicy'
   ,'Grant-CsTeamsCallingPolicy'
   ,'Grant-CsTeamsCallParkPolicy'
   ,'Grant-CsTeamsCallHoldPolicy'
   ,'Grant-CsTeamsChannelsPolicy'
   ,'Grant-CsTeamsComplianceRecordingPolicy'
   ,'Grant-CsTeamsCortanaPolicy'
   ,'Grant-CsTeamsEmergencyCallingPolicy'
   ,'Grant-CsTeamsEmergencyCallRoutingPolicy'
   ,'Grant-CsTeamsFeedbackPolicy'
   ,'Grant-CsTeamsIPPhonePolicy'
   ,'Grant-CsTeamsMeetingBroadcastPolicy'
   ,'Grant-CsTeamsMeetingPolicy'
   ,'Grant-CsTeamsMessagingPolicy'
   ,'Grant-CsTeamsMobilityPolicy'
   ,'Grant-CsTeamsShiftsPolicy'
   ,'Grant-CsTeamsSurvivableBranchAppliancePolicy'
   ,'Grant-CsTeamsUpdateManagementPolicy'
   ,'Grant-CsTeamsUpgradePolicy'
   ,'Grant-CsTeamsVdiPolicy'
   ,'Grant-CsTeamsVerticalPackagePolicy'
   ,'Grant-CsTeamsVideoInteropServicePolicy'
   ,'Grant-CsTeamsWorkLoadPolicy'
   ,'Grant-CsTenantDialPlan'
   ,'Grant-CsVoiceRoutingPolicy'
   ,'Grant-CsTeamsEnhancedEncryptionPolicy'
   ,'Grant-CsTeamsFilesPolicy'
   ,'Import-CsAutoAttendantHolidays'
   ,'Import-CsOnlineAudioFile'
   ,'Invoke-CsUcsRollback'
   ,'Invoke-CsUserPreferredDataLocationSync'
   ,'New-CsApplicationAccessPolicy'
   ,'New-CsAutoAttendant'
   ,'New-CsAutoAttendantCallableEntity'
   ,'New-CsAutoAttendantCallFlow'
   ,'New-CsAutoAttendantCallHandlingAssociation'
   ,'New-CsAutoAttendantDialScope'
   ,'New-CsAutoAttendantMenu'
   ,'New-CsAutoAttendantMenuOption'
   ,'New-CsAutoAttendantPrompt'
   ,'New-CsCallingLineIdentity'
   ,'New-CsCallQueue'
   ,'New-CsClientPolicy'
   ,'New-CsCloudCallDataConnection'
   ,'New-CsConferencingPolicy'
   ,'New-CsDefaultCatalogApp'
   ,'New-CsEdgeAllowAllKnownDomains'
   ,'New-CsEdgeAllowList'
   ,'New-CsEdgeDomainPattern'
   ,'New-CsExternalAccessPolicy'
   ,'New-CsExternalUserCommunicationPolicy'
   ,'New-CsGlobalCatalogApp'
   ,'New-CsHybridPSTNSite'
   ,'New-CsHybridTelephoneNumber'
   ,'New-CsInboundBlockedNumberPattern'
   ,'New-CsInboundExemptNumberPattern'
   ,'New-CsMobilityPolicy'
   ,'New-CsNetworkMediaBypassConfiguration'
   ,'New-CsOnlineApplicationEndpoint'
   ,'New-CsOnlineApplicationInstance'
   ,'New-CsOnlineApplicationInstanceAssociation'
   ,'New-CsOnlineAudioConferencingRoutingPolicy'
   ,'New-CsOnlineAudioFile'
   ,'New-CsOnlineBulkAssignmentInput'
   ,'New-CsOnlineDateTimeRange'
   ,'New-CsOnlineLisCivicAddress'
   ,'New-CsOnlineLisLocation'
   ,'New-CsOnlineNumberPortInOrder'
   ,'New-CsOnlinePSTNGateway'
   ,'New-CsOnlineSchedule'
   ,'New-CsOnlineTimeRange'
   ,'New-CsOnlineVoicemailPolicy'
   ,'New-CsOnlineVoiceRoute'
   ,'New-CsOnlineVoiceRoutingPolicy'
   ,'New-CsTeamsAppPermissionPolicy'
   ,'New-CsTeamsAppPreset'
   ,'New-CsTeamsAppSetupPolicy'
   ,'New-CsTeamsAudioConferencingPolicy'
   ,'New-CsTeamsCallingPolicy'
   ,'New-CsTeamsCallParkPolicy'
   ,'New-CsTeamsCallHoldPolicy'
   ,'New-CsTeamsChannelsPolicy'
   ,'New-CsTeamsComplianceRecordingApplication'
   ,'New-CsTeamsComplianceRecordingPairedApplication'
   ,'New-CsTeamsComplianceRecordingPolicy'
   ,'New-CsTeamsCortanaPolicy'
   ,'New-CsTeamsEmergencyCallingPolicy'
   ,'New-CsTeamsEmergencyCallRoutingPolicy'
   ,'New-CsTeamsEmergencyNumber'
   ,'New-CsTeamsFeedbackPolicy'
   ,'New-CsTeamsIPPhonePolicy'
   ,'New-CsTeamsMeetingBroadcastPolicy'
   ,'New-CsTeamsMeetingPolicy'
   ,'New-CsTeamsMessagingPolicy'
   ,'New-CsTeamsMobilityPolicy'
   ,'New-CsTeamsNetworkRoamingPolicy'
   ,'New-CsTeamsPinnedApp'
   ,'New-CsTeamsShiftsPolicy'
   ,'New-CsTeamsSurvivableBranchAppliance'
   ,'New-CsTeamsSurvivableBranchAppliancePolicy'
   ,'New-CsTeamsTranslationRule'
   ,'New-CsTeamsUpdateManagementPolicy'
   ,'New-CsTeamsVdiPolicy'
   ,'New-CsTeamsVerticalPackagePolicy'
   ,'New-CsTeamsWorkLoadPolicy'
   ,'New-CsTeamsEnhancedEncryptionPolicy'
   ,'New-CsTenantCatalogApp'
   ,'New-CsTenantDialPlan'
   ,'New-CsTenantNetworkPostalCode'
   ,'New-CsTenantNetworkRegion'
   ,'New-CsTenantNetworkSite'
   ,'New-CsTenantNetworkSubnet'
   ,'New-CsTenantTrustedIPAddress'
   ,'New-CsTenantUpdateTimeWindow'
   ,'New-CsVideoInteropServiceProvider'
   ,'New-CsVoiceNormalizationRule'
   ,'New-CsTeamsUnassignedNumberTreatment'
   ,'New-CsTeamsFilesPolicy'
   ,'Register-CsHybridPSTNAppliance'
   ,'Register-CsOnlineDialInConferencingServiceNumber'
   ,'Remove-CsApplicationAccessPolicy'
   ,'Remove-CsAutoAttendant'
   ,'Remove-CsCallingLineIdentity'
   ,'Remove-CsCallQueue'
   ,'Remove-CsClientPolicy'
   ,'Remove-CsConferencingPolicy'
   ,'Remove-CsDefaultCatalogApp'
   ,'Remove-CsExternalAccessPolicy'
   ,'Remove-CsExternalUserCommunicationPolicy'
   ,'Remove-CsGlobalCatalogApp'
   ,'Remove-CsHybridPSTNSite'
   ,'Remove-CsHybridTelephoneNumber'
   ,'Remove-CsInboundBlockedNumberPattern'
   ,'Remove-CsInboundExemptNumberPattern'
   ,'Remove-CsMobilityPolicy'
   ,'Remove-CsOnlineApplicationEndpoint'
   ,'Remove-CsOnlineApplicationInstanceAssociation'
   ,'Remove-CsOnlineAudioConferencingRoutingPolicy'
   ,'Remove-CsOnlineDialInConferencingTenantSettings'
   ,'Remove-CsOnlineLisCivicAddress'
   ,'Remove-CsOnlineLisLocation'
   ,'Remove-CsOnlineLisPort'
   ,'Remove-CsOnlineLisSubnet'
   ,'Remove-CsOnlineLisSwitch'
   ,'Remove-CsOnlineLisWirelessAccessPoint'
   ,'Remove-CsOnlineNumberPortInOrder'
   ,'Remove-CsOnlinePSTNGateway'
   ,'Remove-CsOnlineSchedule'
   ,'Remove-CsOnlineTelephoneNumber'
   ,'Remove-CsOnlineVoicemailPolicy'
   ,'Remove-CsOnlineVoiceRoute'
   ,'Remove-CsOnlineVoiceRoutingPolicy'
   ,'Remove-CsTeamsAppPermissionPolicy'
   ,'Remove-CsTeamsAppPreset'
   ,'Remove-CsTeamsAppSetupPolicy'
   ,'Remove-CsTeamsAudioConferencingPolicy'
   ,'Remove-CsTeamsCallingPolicy'
   ,'Remove-CsTeamsCallParkPolicy'
   ,'Remove-CsTeamsCallHoldPolicy'
   ,'Remove-CsTeamsChannelsPolicy'
   ,'Remove-CsTeamsComplianceRecordingApplication'
   ,'Remove-CsTeamsComplianceRecordingPolicy'
   ,'Remove-CsTeamsCortanaPolicy'
   ,'Remove-CsTeamsEmergencyCallingPolicy'
   ,'Remove-CsTeamsEmergencyCallRoutingPolicy'
   ,'Remove-CsTeamsFeedbackPolicy'
   ,'Remove-CsTeamsIPPhonePolicy'
   ,'Remove-CsTeamsMeetingBroadcastPolicy'
   ,'Remove-CsTeamsMeetingPolicy'
   ,'Remove-CsTeamsMessagingPolicy'
   ,'Remove-CsTeamsMobilityPolicy'
   ,'Remove-CsTeamsNetworkRoamingPolicy'
   ,'Remove-CsTeamsNotificationAndFeedsPolicy'
   ,'Remove-CsTeamsPinnedApp'
   ,'Remove-CsTeamsShiftsPolicy'
   ,'Remove-CsTeamsSurvivableBranchAppliance'
   ,'Remove-CsTeamsSurvivableBranchAppliancePolicy'
   ,'Remove-CsTeamsTargetingPolicy'
   ,'Remove-CsTeamsTranslationRule'
   ,'Remove-CsTeamsUpdateManagementPolicy'
   ,'Remove-CsTeamsVdiPolicy'
   ,'Remove-CsTeamsVerticalPackagePolicy'
   ,'Remove-CsTeamsWorkLoadPolicy'
   ,'Remove-CsTeamsEnhancedEncryptionPolicy'
   ,'Remove-CsTenantCatalogApp'
   ,'Remove-CsTenantDialPlan'
   ,'Remove-CsTenantNetworkConfiguration'
   ,'Remove-CsTenantNetworkPostalCode'
   ,'Remove-CsTenantNetworkRegion'
   ,'Remove-CsTenantNetworkSite'
   ,'Remove-CsTenantNetworkSubnet'
   ,'Remove-CsTenantTrustedIPAddress'
   ,'Remove-CsTenantUpdateTimeWindow'
   ,'Remove-CsVideoInteropServiceProvider'
   ,'Remove-CsVoiceNormalizationRule'
   ,'Remove-CsTeamsUnassignedNumberTreatment'
   ,'Remove-CsTeamsFilesPolicy'
   ,'Search-CsOnlineTelephoneNumberInventory'
   ,'Select-CsOnlineTelephoneNumberInventory'
   ,'Set-CsApplicationAccessPolicy'
   ,'Set-CsApplicationMeetingConfiguration'
   ,'Set-CsAutoAttendant'
   ,'Set-CsBroadcastMeetingConfiguration'
   ,'Set-CsCallingLineIdentity'
   ,'Set-CsCallQueue'
   ,'Set-CsCceApplianceConfigurationReplicationStatus'
   ,'Set-CsCceApplianceDeploymentStatus'
   ,'Set-CsCceApplianceStatus'
   ,'Set-CsClientPolicy'
   ,'Set-CsConferencingPolicy'
   ,'Set-CsDefaultCatalogApp'
   ,'Set-CsExternalAccessPolicy'
   ,'Set-CsExternalUserCommunicationPolicy'
   ,'Set-CsGlobalCatalogApp'
   ,'Set-CsHybridMediationServer'
   ,'Set-CsHybridPSTNAppliance'
   ,'Set-CsHybridPSTNSite'
   ,'Set-CsInboundBlockedNumberPattern'
   ,'Set-CsInboundExemptNumberPattern'
   ,'Set-CsIPPhonePolicy'
   ,'Set-CsMeetingConfiguration'
   ,'Set-CsMeetingRoom'
   ,'Set-CsMobilityPolicy'
   ,'Set-CsNetworkConfiguration'
   ,'Set-CsOAuthConfiguration'
   ,'Set-CsOnlineApplicationEndpoint'
   ,'Set-CsOnlineApplicationInstance'
   ,'Set-CsOnlineAudioConferencingRoutingPolicy'
   ,'Set-CsOnlineDialInConferencingBridge'
   ,'Set-CsOnlineDialInConferencingServiceNumber'
   ,'Set-CsOnlineDialInConferencingTenantSettings'
   ,'Set-CsOnlineDialInConferencingUser'
   ,'Set-CsOnlineDialInConferencingUserDefaultNumber'
   ,'Set-CsOnlineDirectoryUser'
   ,'Set-CsOnlineEnhancedEmergencyServiceDisclaimer'
   ,'Set-CsOnlineLisCivicAddress'
   ,'Set-CsOnlineLisLocation'
   ,'Set-CsOnlineLisPort'
   ,'Set-CsOnlineLisSubnet'
   ,'Set-CsOnlineLisSwitch'
   ,'Set-CsOnlineLisWirelessAccessPoint'
   ,'Set-CsOnlineNumberPortInOrder'
   ,'Set-CsOnlineNumberPortOutOrderPin'
   ,'Set-CsOnlinePSTNGateway'
   ,'Set-CsOnlinePstnUsage'
   ,'Set-CsOnlineSchedule'
   ,'Set-CsOnlineVoiceApplicationInstance'
   ,'Set-CsOnlineVoicemailPolicy'
   ,'Set-CsOnlineVoicemailUserSettings'
   ,'Set-CsOnlineVoiceRoute'
   ,'Set-CsOnlineVoiceRoutingPolicy'
   ,'Set-CsOnlineVoiceUser'
   ,'Set-CsOnlineVoiceUserBulk'
   ,'Set-CsPrivacyConfiguration'
   ,'Set-CsPushNotificationConfiguration'
   ,'Set-CsTeamsAcsFederationConfiguration'
   ,'Set-CsTeamsAppPermissionPolicy'
   ,'Set-CsTeamsAppPreset'
   ,'Set-CsTeamsAppSetupPolicy'
   ,'Set-CsTeamsAudioConferencingPolicy'
   ,'Set-CsTeamsCallingPolicy'
   ,'Set-CsTeamsCallParkPolicy'
   ,'Set-CsTeamsCallHoldPolicy'
   ,'Set-CsTeamsChannelsPolicy'
   ,'Set-CsTeamsClientConfiguration'
   ,'Set-CsTeamsComplianceRecordingApplication'
   ,'Set-CsTeamsComplianceRecordingPolicy'
   ,'Set-CsTeamsCortanaPolicy'
   ,'Set-CsTeamsEducationAssignmentsAppPolicy'
   ,'Set-CsTeamsEmergencyCallingPolicy'
   ,'Set-CsTeamsEmergencyCallRoutingPolicy'
   ,'Set-CsTeamsFeedbackPolicy'
   ,'Set-CsTeamsGuestCallingConfiguration'
   ,'Set-CsTeamsGuestMeetingConfiguration'
   ,'Set-CsTeamsGuestMessagingConfiguration'
   ,'Set-CsTeamsIPPhonePolicy'
   ,'Set-CsTeamsMeetingBroadcastConfiguration'
   ,'Set-CsTeamsMeetingBroadcastPolicy'
   ,'Set-CsTeamsMeetingConfiguration'
   ,'Set-CsTeamsMeetingPolicy'
   ,'Set-CsTeamsMessagingPolicy'
   ,'Set-CsTeamsMigrationConfiguration'
   ,'Set-CsTeamsMobilityPolicy'
   ,'Set-CsTeamsNetworkRoamingPolicy'
   ,'Set-CsTeamsNotificationAndFeedsPolicy'
   ,'Set-CsTeamsPinnedApp'
   ,'Set-CsTeamsShiftsAppPolicy'
   ,'Set-CsTeamsShiftsPolicy'
   ,'Set-CsTeamsSurvivableBranchAppliance'
   ,'Set-CsTeamsSurvivableBranchAppliancePolicy'
   ,'Set-CsTeamsTargetingPolicy'
   ,'Set-CsTeamsTranslationRule'
   ,'Set-CsTeamsUpdateManagementPolicy'
   ,'Set-CsTeamsUpgradeConfiguration'
   ,'Set-CsTeamsUpgradeStatus'
   ,'Set-CsTeamsVdiPolicy'
   ,'Set-CsTeamsVerticalPackagePolicy'
   ,'Set-CsTeamsWorkLoadPolicy'
   ,'Set-CsTenantBlockedCallingNumbers'
   ,'Set-CsTeamsEnhancedEncryptionPolicy'
   ,'Set-CsTenantCatalogApp'
   ,'Set-CsTenantDialPlan'
   ,'Set-CsTenantFederationConfiguration'
   ,'Set-CsTenantHybridConfiguration'
   ,'Set-CsTenantMigrationConfiguration'
   ,'Set-CsTenantNetworkConfiguration'
   ,'Set-CsTenantNetworkPostalCode'
   ,'Set-CsTenantNetworkRegion'
   ,'Set-CsTenantNetworkSite'
   ,'Set-CsTenantNetworkSubnet'
   ,'Set-CsTenantPublicProvider'
   ,'Set-CsTenantTrustedIPAddress'
   ,'Set-CsTenantUpdateTimeWindow'
   ,'Set-CsUCPhoneConfiguration'
   ,'Set-CsUser'
   ,'Set-CsUserPstnSettings'
   ,'Set-CsUserServicesPolicy'
   ,'Set-CsVideoInteropServiceProvider'
   ,'Set-CsVoiceNormalizationRule'
   ,'Set-CsTeamsUnassignedNumberTreatment'
   ,'Set-CsTeamsFilesPolicy'
   ,'Start-CsExMeetingMigration'
   ,'Switch-CsOnlineApplicationEndpoint'
   ,'Sync-CsOnlineApplicationInstance'
   ,'Test-CsEffectiveTenantDialPlan'
   ,'Test-CsInboundBlockedNumberPattern'
   ,'Test-CsOnlineCarrierPortabilityIn'
   ,'Test-CsOnlineLisCivicAddress'
   ,'Test-CsOnlinePortabilityIn'
   ,'Test-CsVoiceNormalizationRule'
   ,'Unregister-CsHybridPSTNAppliance'
   ,'Unregister-CsOnlineDialInConferencingServiceNumber'
   ,'Update-CsAutoAttendant'
   ,'Update-CsTenantMeetingUrl'
#SfBO: End
)
# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @(
    'Add-TeamChannelUser'
    ,'Add-TeamUser'
    ,'Connect-MicrosoftTeams'
    ,'Disconnect-MicrosoftTeams'
    ,'Get-MultiGeoRegion'
    ,'Get-Operation'
    ,'Get-Team'
    ,'Get-TeamChannel'
    ,'Get-TeamChannelUser'
    ,'Get-TeamsApp'
    ,'Get-TeamUser'
    ,'New-Team'
    ,'New-TeamChannel'
    ,'New-TeamsApp'
    ,'Remove-Team'
    ,'Remove-TeamChannel'
    ,'Remove-TeamChannelUser'
    ,'Remove-TeamsApp'
    ,'Remove-TeamUser'
    ,'Set-Team'
    ,'Set-TeamArchivedState'
    ,'Set-TeamChannel'
    ,'Set-TeamPicture'
    ,'Set-TeamsApp'
#preview    ,'Add-TeamsAppInstallation'
#preview    ,'Get-TeamsAppInstallation'
#preview    ,'Get-TeamTargetingHierarchyStatus'
#preview    ,'Remove-TeamsAppInstallation'
#preview    ,'Remove-TeamTargetingHierarchy'
#preview    ,'Set-TeamTargetingHierarchy'
#preview    ,'Update-TeamsAppInstallation'
#preview    ,'Get-LicenseReportForChangeNotificationSubscription'
 )

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{
    PSData = @{
        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Office365', 'MicrosoftTeams', 'Teams'

        # A URL to the license for this module.
        LicenseUri = 'https://raw.githubusercontent.com/MicrosoftDocs/office-docs-powershell/master/teams/LICENSE.txt'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/MicrosoftDocs/office-docs-powershell/tree/master/teams'

        # A URL to an icon representing this module.
        IconUri = 'https://statics.teams.microsoft.com/evergreen-assets/apps/teamscmdlets_largeimage.png'

        # Appends prerelease string to version
        Prerelease = ''

        # ReleaseNotes of this module
        ReleaseNotes = @'
 **3.1.0-GA** (The project - MicrosoftTeams contains these changes so far for this release)

- Renamed Cmdlet from Get-CsTeamsShiftsConnectionUser to Get-CsTeamsShiftsConnectionWfmUser.
- Releases new parameters ResultSize, SkipUserPolicies for Get-CsOnlineUser. 
- Releases new parameters ResultSize for Get-CsOnlineDialInConferencingUser.
- Releases new parameters First, NumberAssigned, NumberNotAssigned, PSTNConnectivity, EnterpriseVoiceStatus, CivicAddressId, LocationId for Get-CsOnlineVoiceUser.
- The complete release notes can be found in the below link:
https://docs.microsoft.com/MicrosoftTeams/teams-powershell-release-notes
'@
    } # End of PSData hashtable
} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''
}

# SIG # Begin signature block
# MIInowYJKoZIhvcNAQcCoIInlDCCJ5ACAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCDsIRRS4DYhgjPb
# iamDIn7f5tRfQykRlMopTbTMd7gjsqCCDXMwggXxMIID2aADAgECAhMzAAACGYwK
# n7IWKxDmAAAAAAIZMA0GCSqGSIb3DQEBCwUAMH4xCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNpZ25p
# bmcgUENBIDIwMTEwHhcNMjEwNDI5MTkxMjU1WhcNMjIwNDI4MTkxMjU1WjByMQsw
# CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
# ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMRwwGgYDVQQDExNTa3lw
# ZSBTb2Z0d2FyZSBTYXJsMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
# nxMscK0w8ebaayvQhxPtLTkomfivSX4yNLmQJGXG+1yUKU4fmdQAhZm5mSIdFAEv
# sjAwCP3vUmh2N5R5TrAN/whfjGcDDlCYonKcrmuSaXxGuyjXKlELlRmPOaobqeo1
# 1Amcz6SRbNYBtKtRiP5ip2PfAvtJp7AvH0mZfGXKehE4C+5t8XYZ3K1JU3Tdb+3Z
# z+smovI8h/ZPe+uV2ORTxxa9kBLDvueJZbzKkn/WAIX/8rq/ywHtffSTXSueUmoe
# NJ0UCyoNBr90xtnozaCVknyRG8qWzHEZlc43FPNwIW6y8k1JSuspq+SML/HP7Fjv
# 7zcTLtM1HBBX/I9KxBJSBQIDAQABo4IBcjCCAW4wEwYDVR0lBAwwCgYIKwYBBQUH
# AwMwHQYDVR0OBBYEFAZqNYGuvWVnCVhV5aJBAvx4cJdwMFAGA1UdEQRJMEekRTBD
# MSkwJwYDVQQLEyBNaWNyb3NvZnQgT3BlcmF0aW9ucyBQdWVydG8gUmljbzEWMBQG
# A1UEBRMNMjMwMjU0KzQ2NDU2MjAfBgNVHSMEGDAWgBRIbmTlUAXTgqoXNzcitW2o
# ynUClTBUBgNVHR8ETTBLMEmgR6BFhkNodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20v
# cGtpb3BzL2NybC9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3JsMGEGCCsG
# AQUFBwEBBFUwUzBRBggrBgEFBQcwAoZFaHR0cDovL3d3dy5taWNyb3NvZnQuY29t
# L3BraW9wcy9jZXJ0cy9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3J0MAwG
# A1UdEwEB/wQCMAAwDQYJKoZIhvcNAQELBQADggIBABRKE3yDcJHa8xnyFn9Z+0m8
# vQLeUGC9933o78aSOWDkvcPFPczSqvw4cUmQnHPcRwDS1mwlYs5TmCdIS6Ij++Or
# uWxfgMdPRpveO6zT8rDWBL2sqCT/k5yCO75DVhT4kE/qEe81T4OY/Ejx3lZbBE1a
# z2k5dOL/ZWqNu8FdKSDmBZEeENOYy9UIyLf6coV2KLERB2IZ3W8U3z37fPA5nRMw
# +9sWWb98Gdm8exr4UwmnU0q8Y0KvJx/xwqOPShgiDjHsWev3fzsKSYzebkfBdLbw
# DZl9880mrGr03CfEWGDWa0tJui3LRh4csIuxWHkUrFw/R2N8baMDGPEUCh7dE+qf
# nuuMJ5tRUmnMOqyqj8dLXUZa+yxxpS91qde5asle0+WfzjLQ1D+T6ElhLBQU9LNh
# 5nhbD1+kJkVHFAU2tM3MXa2tgMVWFWQP4IqcQDWMW68M90VkGUrJ+t63oRO8HwbL
# 4IZJxG0wW/527ypSQTmpLSX6mM2vIyFHsO4zCvjDq8yfnDk25bpUNJbfOpqVkkWP
# UE+4bNIQbzcWgKgPIZDOka3pxq4vI05ns3tnvWS7TKiG+7ZYr5ZBSS6pr1Wykt0U
# aXxaUZuAWwikj2gvZAXR35f5bDg+36WoJTpQKNqzsY7dyL6SxkcZI8DcEKWEfbWd
# BX8q+w5hzEWqh7TrYJ93MIIHejCCBWKgAwIBAgIKYQ6Q0gAAAAAAAzANBgkqhkiG
# 9w0BAQsFADCBiDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAO
# BgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEy
# MDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2VydGlmaWNhdGUgQXV0aG9yaXR5IDIw
# MTEwHhcNMTEwNzA4MjA1OTA5WhcNMjYwNzA4MjEwOTA5WjB+MQswCQYDVQQGEwJV
# UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UE
# ChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQgQ29k
# ZSBTaWduaW5nIFBDQSAyMDExMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKC
# AgEAq/D6chAcLq3YbqqCEE00uvK2WCGfQhsqa+laUKq4BjgaBEm6f8MMHt03a8YS
# 2AvwOMKZBrDIOdUBFDFC04kNeWSHfpRgJGyvnkmc6Whe0t+bU7IKLMOv2akrrnoJ
# r9eWWcpgGgXpZnboMlImEi/nqwhQz7NEt13YxC4Ddato88tt8zpcoRb0RrrgOGSs
# bmQ1eKagYw8t00CT+OPeBw3VXHmlSSnnDb6gE3e+lD3v++MrWhAfTVYoonpy4BI6
# t0le2O3tQ5GD2Xuye4Yb2T6xjF3oiU+EGvKhL1nkkDstrjNYxbc+/jLTswM9sbKv
# kjh+0p2ALPVOVpEhNSXDOW5kf1O6nA+tGSOEy/S6A4aN91/w0FK/jJSHvMAhdCVf
# GCi2zCcoOCWYOUo2z3yxkq4cI6epZuxhH2rhKEmdX4jiJV3TIUs+UsS1Vz8kA/DR
# elsv1SPjcF0PUUZ3s/gA4bysAoJf28AVs70b1FVL5zmhD+kjSbwYuER8ReTBw3J6
# 4HLnJN+/RpnF78IcV9uDjexNSTCnq47f7Fufr/zdsGbiwZeBe+3W7UvnSSmnEyim
# p31ngOaKYnhfsi+E11ecXL93KCjx7W3DKI8sj0A3T8HhhUSJxAlMxdSlQy90lfdu
# +HggWCwTXWCVmj5PM4TasIgX3p5O9JawvEagbJjS4NaIjAsCAwEAAaOCAe0wggHp
# MBAGCSsGAQQBgjcVAQQDAgEAMB0GA1UdDgQWBBRIbmTlUAXTgqoXNzcitW2oynUC
# lTAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTALBgNVHQ8EBAMCAYYwDwYDVR0T
# AQH/BAUwAwEB/zAfBgNVHSMEGDAWgBRyLToCMZBDuRQFTuHqp8cx0SOJNDBaBgNV
# HR8EUzBRME+gTaBLhklodHRwOi8vY3JsLm1pY3Jvc29mdC5jb20vcGtpL2NybC9w
# cm9kdWN0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3JsMF4GCCsGAQUF
# BwEBBFIwUDBOBggrBgEFBQcwAoZCaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3Br
# aS9jZXJ0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3J0MIGfBgNVHSAE
# gZcwgZQwgZEGCSsGAQQBgjcuAzCBgzA/BggrBgEFBQcCARYzaHR0cDovL3d3dy5t
# aWNyb3NvZnQuY29tL3BraW9wcy9kb2NzL3ByaW1hcnljcHMuaHRtMEAGCCsGAQUF
# BwICMDQeMiAdAEwAZQBnAGEAbABfAHAAbwBsAGkAYwB5AF8AcwB0AGEAdABlAG0A
# ZQBuAHQALiAdMA0GCSqGSIb3DQEBCwUAA4ICAQBn8oalmOBUeRou09h0ZyKbC5YR
# 4WOSmUKWfdJ5DJDBZV8uLD74w3LRbYP+vj/oCso7v0epo/Np22O/IjWll11lhJB9
# i0ZQVdgMknzSGksc8zxCi1LQsP1r4z4HLimb5j0bpdS1HXeUOeLpZMlEPXh6I/MT
# faaQdION9MsmAkYqwooQu6SpBQyb7Wj6aC6VoCo/KmtYSWMfCWluWpiW5IP0wI/z
# Rive/DvQvTXvbiWu5a8n7dDd8w6vmSiXmE0OPQvyCInWH8MyGOLwxS3OW560STkK
# xgrCxq2u5bLZ2xWIUUVYODJxJxp/sfQn+N4sOiBpmLJZiWhub6e3dMNABQamASoo
# PoI/E01mC8CzTfXhj38cbxV9Rad25UAqZaPDXVJihsMdYzaXht/a8/jyFqGaJ+HN
# pZfQ7l1jQeNbB5yHPgZ3BtEGsXUfFL5hYbXw3MYbBL7fQccOKO7eZS/sl/ahXJbY
# ANahRr1Z85elCUtIEJmAH9AAKcWxm6U/RXceNcbSoqKfenoi+kiVH6v7RyOA9Z74
# v2u3S5fi63V4GuzqN5l5GEv/1rMjaHXmr/r8i+sLgOppO6/8MO0ETI7f33VtY5E9
# 0Z1WTk+/gFcioXgRMiF670EKsT/7qMykXcGhiJtXcVZOSEXAQsmbdlsKgEhr/Xmf
# wb1tbWrJUnMTDXpQzTGCGYYwghmCAgEBMIGVMH4xCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNpZ25p
# bmcgUENBIDIwMTECEzMAAAIZjAqfshYrEOYAAAAAAhkwDQYJYIZIAWUDBAIBBQCg
# gaYwGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEOMAwG
# CisGAQQBgjcCARUwLwYJKoZIhvcNAQkEMSIEIGrvLnO1CguGDO22C8F6PxlAP2zE
# We9uuNqErf1W0lwtMDoGCisGAQQBgjcCAQwxLDAqoAyACgBTAGsAeQBwAGWhGoAY
# aHR0cDovL3d3dy5taWNyb3NvZnQuY29tMA0GCSqGSIb3DQEBAQUABIIBADpuTStI
# 5lJR0OlECSBL3zpEZPtvqs4gR2D/7j+of20SOzPmEdk84aVpwP3uAGS/4akLL0hr
# 3be1JxkTVYy55GHd5JRKmZ9NwzW5ubKegoixKAPuY0anERcwfarWeRX68pboB+Lv
# rlxPpUtfy1XFY06ZZtDSZKIJYxC1GvfcKyF6R7lCUwiBmMF+vnNxowhYDzGml9Xv
# 1XoIqjLkn+o/GUiMKiqaWq516rntc3rn5RrLQ8doZRsMzJKdCKzuCL1JjVyQL0Mo
# 55UWtYX0lfkcuwAaWfECsRUxEFD/0P53LHspl94P2Pfzd3B5yjpTfWprtF/5WJ1S
# RN30PHa4HzLCMmuhghcYMIIXFAYKKwYBBAGCNwMDATGCFwQwghcABgkqhkiG9w0B
# BwKgghbxMIIW7QIBAzEPMA0GCWCGSAFlAwQCAQUAMIIBWAYLKoZIhvcNAQkQAQSg
# ggFHBIIBQzCCAT8CAQEGCisGAQQBhFkKAwEwMTANBglghkgBZQMEAgEFAAQgtZoj
# 4tvupFU5WlL6asrYcfV9k6p5qcPVhLMnELFKpvQCBmHCTCI+NRgSMjAyMjAxMjEw
# ODQzNDguNTRaMASAAgH0oIHYpIHVMIHSMQswCQYDVQQGEwJVUzETMBEGA1UECBMK
# V2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0
# IENvcnBvcmF0aW9uMS0wKwYDVQQLEyRNaWNyb3NvZnQgSXJlbGFuZCBPcGVyYXRp
# b25zIExpbWl0ZWQxJjAkBgNVBAsTHVRoYWxlcyBUU1MgRVNOOkZDNDEtNEJENC1E
# MjIwMSUwIwYDVQQDExxNaWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2aWNloIIRaDCC
# BxQwggT8oAMCAQICEzMAAAGOWdtGAKgQlMwAAQAAAY4wDQYJKoZIhvcNAQELBQAw
# fDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1Jl
# ZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMd
# TWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTAwHhcNMjExMDI4MTkyNzQ1WhcN
# MjMwMTI2MTkyNzQ1WjCB0jELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0
# b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3Jh
# dGlvbjEtMCsGA1UECxMkTWljcm9zb2Z0IElyZWxhbmQgT3BlcmF0aW9ucyBMaW1p
# dGVkMSYwJAYDVQQLEx1UaGFsZXMgVFNTIEVTTjpGQzQxLTRCRDQtRDIyMDElMCMG
# A1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAgU2VydmljZTCCAiIwDQYJKoZIhvcN
# AQEBBQADggIPADCCAgoCggIBAKojAqujjMy2ucK7XH+wX/X9Vl1vZKamzgc4Dyb2
# hi62Ru7cIMKk0Vn9RZI6SSgThuUDyEcu2uiBVQMtFvrQWhV+CJ+A2wX9rRrm8mPf
# oUVPoUXsDyR+QmDr6T4e+xXxjOt/jpcEV6eWBEerQtFkSp95q8lqbeAsAA7hr9Cw
# 9kI54YYLUVYnbIg55/fmi4zLjWqVIbLRqgq+yXEGbdGaz1B1v06kycpnlNXqoDaK
# xG03nelEMi2k1QJoVzUFwwoX2udup1u0UOy+LV1/S3NKILogkpD5buXazQOjTPM/
# lF0DgB8VXyEF5ovmN0ldoa9nXMW8vZ5U82L3+GQ6+VqXMLe7U3USCYm1x7F1jCq5
# js4pYhg06C8d+Gv3LWRODTi55aykFjfWRvjsec0WqytRIUoWoTNLkDYW+gSY6d/n
# NHjczBSdqi2ag6dv92JeUPuJPjAxy04qT+lQXcXHVX3eJoK1U8d2nzuSjX4DJ4Bh
# n4UmsBq2kVtvBIayzrKZiMYovdhO7453CdrXI4SwowQK1aT4d3GRuYN2VcuYogGq
# A2rMKTYJzBQCuVJ9a3ivjBYT4vYjJ71D8LUwwybeWBA+QwE95gVMaeUB97e0YWcA
# CTS1i7aU3hhe7m/NbEimL9mq3WswHvVy0tdLVdqDj63J4hic5V1u1T78akDcXvJQ
# gwNtAgMBAAGjggE2MIIBMjAdBgNVHQ4EFgQU7EH5M/YE+ODf+RvLzR2snqfmleQw
# HwYDVR0jBBgwFoAUn6cVXQBeYl2D9OXSZacbUzUZ6XIwXwYDVR0fBFgwVjBUoFKg
# UIZOaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9jcmwvTWljcm9zb2Z0
# JTIwVGltZS1TdGFtcCUyMFBDQSUyMDIwMTAoMSkuY3JsMGwGCCsGAQUFBwEBBGAw
# XjBcBggrBgEFBQcwAoZQaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9j
# ZXJ0cy9NaWNyb3NvZnQlMjBUaW1lLVN0YW1wJTIwUENBJTIwMjAxMCgxKS5jcnQw
# DAYDVR0TAQH/BAIwADATBgNVHSUEDDAKBggrBgEFBQcDCDANBgkqhkiG9w0BAQsF
# AAOCAgEANVCvccyHk5SoUmy59G3pEeYGIemwdV0KZbgqggNebJGd+1IpWhScPPhp
# JQy85TYUj9pjojs1cgqvJJKap31HNNWWgXs0MYO+6nr49ojMoN/WCX3ogiIcWDhb
# oMHqWKzzvDJQf6Lnv1YSIg29XjWE5T0pr96WpbILZK29KKNBdLlpl+BEFRikaNFB
# DbWXrVSMWtCfQ6VHY0Fj3hIfXBDPkYBNuucOVgFW/ljcdIloheIk2wpq1mlRDl/d
# nTagZvW09VO5xsDeQsoKTQIBGmJ60zMdTeAI8TmwAgzeQ3bxpbvztA3zFlXOqpOo
# igxQulqV0EpDJa5VyCPzYaftPp6FOrXxKRyi7e32JvaH+Yv0KJnAsKP3pIjgo2JL
# ad/d6L6AtTtri7Wy5zFZROa2gSwTUmyDWekC8YgONZV51VSyMw4oVC/DFPQjLxuL
# HW4ZNhV/M767D+T3gSMNX2npzGbs9Fd1FwrVOTpMeX5oqFooi2UgotZY2sV/gRME
# IopwovrxOfW02CORW7kfLQ7hi4lbvyUqVRV681jD9ip9dbAiwBhI6iWFJjtbUWNv
# Snex3CI9p4kgdD0Dgo2JZwp8sJw4p6ktQl70bIrI1ZUtUaeE5rpLPqRsYjBsxefM
# 3G/oaBSsjjbi92/rYMUwM97BdwVV/bpPTORfjhKHsi8hny3pDQIwggdxMIIFWaAD
# AgECAhMzAAAAFcXna54Cm0mZAAAAAAAVMA0GCSqGSIb3DQEBCwUAMIGIMQswCQYD
# VQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEe
# MBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMTIwMAYDVQQDEylNaWNyb3Nv
# ZnQgUm9vdCBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkgMjAxMDAeFw0yMTA5MzAxODIy
# MjVaFw0zMDA5MzAxODMyMjVaMHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNo
# aW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29y
# cG9yYXRpb24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEw
# MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA5OGmTOe0ciELeaLL1yR5
# vQ7VgtP97pwHB9KpbE51yMo1V/YBf2xK4OK9uT4XYDP/XE/HZveVU3Fa4n5KWv64
# NmeFRiMMtY0Tz3cywBAY6GB9alKDRLemjkZrBxTzxXb1hlDcwUTIcVxRMTegCjhu
# je3XD9gmU3w5YQJ6xKr9cmmvHaus9ja+NSZk2pg7uhp7M62AW36MEBydUv626GIl
# 3GoPz130/o5Tz9bshVZN7928jaTjkY+yOSxRnOlwaQ3KNi1wjjHINSi947SHJMPg
# yY9+tVSP3PoFVZhtaDuaRr3tpK56KTesy+uDRedGbsoy1cCGMFxPLOJiss254o2I
# 5JasAUq7vnGpF1tnYN74kpEeHT39IM9zfUGaRnXNxF803RKJ1v2lIH1+/NmeRd+2
# ci/bfV+AutuqfjbsNkz2K26oElHovwUDo9Fzpk03dJQcNIIP8BDyt0cY7afomXw/
# TNuvXsLz1dhzPUNOwTM5TI4CvEJoLhDqhFFG4tG9ahhaYQFzymeiXtcodgLiMxhy
# 16cg8ML6EgrXY28MyTZki1ugpoMhXV8wdJGUlNi5UPkLiWHzNgY1GIRH29wb0f2y
# 1BzFa/ZcUlFdEtsluq9QBXpsxREdcu+N+VLEhReTwDwV2xo3xwgVGD94q0W29R6H
# XtqPnhZyacaue7e3PmriLq0CAwEAAaOCAd0wggHZMBIGCSsGAQQBgjcVAQQFAgMB
# AAEwIwYJKwYBBAGCNxUCBBYEFCqnUv5kxJq+gpE8RjUpzxD/LwTuMB0GA1UdDgQW
# BBSfpxVdAF5iXYP05dJlpxtTNRnpcjBcBgNVHSAEVTBTMFEGDCsGAQQBgjdMg30B
# ATBBMD8GCCsGAQUFBwIBFjNodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3Bz
# L0RvY3MvUmVwb3NpdG9yeS5odG0wEwYDVR0lBAwwCgYIKwYBBQUHAwgwGQYJKwYB
# BAGCNxQCBAweCgBTAHUAYgBDAEEwCwYDVR0PBAQDAgGGMA8GA1UdEwEB/wQFMAMB
# Af8wHwYDVR0jBBgwFoAU1fZWy4/oolxiaNE9lJBb186aGMQwVgYDVR0fBE8wTTBL
# oEmgR4ZFaHR0cDovL2NybC5taWNyb3NvZnQuY29tL3BraS9jcmwvcHJvZHVjdHMv
# TWljUm9vQ2VyQXV0XzIwMTAtMDYtMjMuY3JsMFoGCCsGAQUFBwEBBE4wTDBKBggr
# BgEFBQcwAoY+aHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraS9jZXJ0cy9NaWNS
# b29DZXJBdXRfMjAxMC0wNi0yMy5jcnQwDQYJKoZIhvcNAQELBQADggIBAJ1Vffwq
# reEsH2cBMSRb4Z5yS/ypb+pcFLY+TkdkeLEGk5c9MTO1OdfCcTY/2mRsfNB1OW27
# DzHkwo/7bNGhlBgi7ulmZzpTTd2YurYeeNg2LpypglYAA7AFvonoaeC6Ce5732pv
# vinLbtg/SHUB2RjebYIM9W0jVOR4U3UkV7ndn/OOPcbzaN9l9qRWqveVtihVJ9Ak
# vUCgvxm2EhIRXT0n4ECWOKz3+SmJw7wXsFSFQrP8DJ6LGYnn8AtqgcKBGUIZUnWK
# NsIdw2FzLixre24/LAl4FOmRsqlb30mjdAy87JGA0j3mSj5mO0+7hvoyGtmW9I/2
# kQH2zsZ0/fZMcm8Qq3UwxTSwethQ/gpY3UA8x1RtnWN0SCyxTkctwRQEcb9k+SS+
# c23Kjgm9swFXSVRk2XPXfx5bRAGOWhmRaw2fpCjcZxkoJLo4S5pu+yFUa2pFEUep
# 8beuyOiJXk+d0tBMdrVXVAmxaQFEfnyhYWxz/gq77EFmPWn9y8FBSX5+k77L+Dvk
# txW/tM4+pTFRhLy/AsGConsXHRWJjXD+57XQKBqJC4822rpM+Zv/Cuk0+CQ1Zyvg
# DbjmjJnW4SLq8CdCPSWU5nR0W2rRnj7tfqAxM328y+l7vzhwRNGQ8cirOoo6CGJ/
# 2XBjU02N7oJtpQUQwXEGahC0HVUzWLOhcGbyoYIC1zCCAkACAQEwggEAoYHYpIHV
# MIHSMQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
# UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMS0wKwYDVQQL
# EyRNaWNyb3NvZnQgSXJlbGFuZCBPcGVyYXRpb25zIExpbWl0ZWQxJjAkBgNVBAsT
# HVRoYWxlcyBUU1MgRVNOOkZDNDEtNEJENC1EMjIwMSUwIwYDVQQDExxNaWNyb3Nv
# ZnQgVGltZS1TdGFtcCBTZXJ2aWNloiMKAQEwBwYFKw4DAhoDFQA9YivqT04R6oKW
# ucbD5omK7llbjKCBgzCBgKR+MHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNo
# aW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29y
# cG9yYXRpb24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEw
# MA0GCSqGSIb3DQEBBQUAAgUA5ZRWajAiGA8yMDIyMDEyMTA1NDUxNFoYDzIwMjIw
# MTIyMDU0NTE0WjB3MD0GCisGAQQBhFkKBAExLzAtMAoCBQDllFZqAgEAMAoCAQAC
# AgvtAgH/MAcCAQACAhHzMAoCBQDllafqAgEAMDYGCisGAQQBhFkKBAIxKDAmMAwG
# CisGAQQBhFkKAwKgCjAIAgEAAgMHoSChCjAIAgEAAgMBhqAwDQYJKoZIhvcNAQEF
# BQADgYEAb1S5vn2hdWuxNQP8q8oQ2vBpkMMXl2M8MdXgWkz/qQgUhkrpHgB46DxS
# 2pXca5o4rfjZddS6ZMo4Tqp+WTx1zdBwbaem04LI85fJ4JyQeAYs4XIlbvFHH8AP
# Nc2CcCuckTLr2p6MgJnrsVQyntG698baZPa07s818M+6lfnmG2QxggQNMIIECQIB
# ATCBkzB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UE
# BxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYD
# VQQDEx1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMAITMwAAAY5Z20YAqBCU
# zAABAAABjjANBglghkgBZQMEAgEFAKCCAUowGgYJKoZIhvcNAQkDMQ0GCyqGSIb3
# DQEJEAEEMC8GCSqGSIb3DQEJBDEiBCDHpF4E32M8d8aMaMiUbwy8mtht4gAp8G8/
# Nt0MspyMPzCB+gYLKoZIhvcNAQkQAi8xgeowgecwgeQwgb0EIL0FjyE74oGlLlef
# n/5VrNwV2cCf5dZn/snpbuZ15sQlMIGYMIGApH4wfDELMAkGA1UEBhMCVVMxEzAR
# BgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1p
# Y3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3Rh
# bXAgUENBIDIwMTACEzMAAAGOWdtGAKgQlMwAAQAAAY4wIgQgno09iDqCxzLXFO4q
# s1KBOYsOygrbK0dnpnRRVmKwLKswDQYJKoZIhvcNAQELBQAEggIAZKGYN+zdWJyT
# 1jqrZA/UYNPv6j8JbBhiip6UJHXfJDipad5bC6XuPFFmZBlw1D5Ja/XoZ9roiSZJ
# ZT/CcFXuuT6mKwG1r4xAhFK2hMStt5QTu/XsHWPHlbYZVZkECsG3faATTBKnP1W6
# kbMYYrJbQcFnsNzTWX0bjJ4awYezwLCR1Jhlq/e/af0a5aeZnwsI8KARWArAP1Zu
# 2rtch88fwdX7JpActgCGf/+oDpLa1F6kaPxNmtTSAgc0XvQyx6szCFWlS3KrnhMf
# IAKPH0yMZTbFnSbioxrkFJxt9QW4Tn7wCYXMlMouwwzeHNNN2ThkSyv4FkrYYJ/X
# vK22rCgYr4YpPHMKdRYL77CadtnPuOpDi06CV6YLwpyIX7wuNoM2ADKZbXhyUR1u
# mgtw2+A3/opqoVS21UruclAgofzJtIMg1MY+l3geN/rgiC5i5lhA+Enk1S0XR0+p
# BgzCTDk4kNPGW4VIGP87O1b+9jezPsmFMxCSFyXAVKvC+kpn15lzRAg10ZcQbTbp
# /3O/0VmNRFU2J3s5qev/cMiU45aSEPHIt1qr4S5E09tf2no1kWyeL1B1g6WxsHQb
# iLchnbGPbX2yDzjPNJuNVV3LH7DGrweEaqMr/Fz9C29YkIoZQxItmHKSC8Dqh5nu
# UdlANwyQ/efzrEZvzyxUSPf2txptvw4=
# SIG # End signature block
